import React from 'react';
import {AbsoluteFill, Audio, Img, Sequence, interpolate, spring, staticFile, useCurrentFrame, useVideoConfig} from 'remotion';
import {Minecraftfiliz, Minecraftibrahim} from '../MinecraftCharacter';
import timings from './gunes_timings.json';

type Scene = {id: string; title: string; image: string; focus: string; points: string[]; firstSpeaker: 'filiz' | 'ibrahim'; splitSec: number; totalSec: number; visualKind: string};

const sceneTexts = [
  {id: '01', title: 'Güneş: Yaşam Kaynağımız', image: 'gunes_1.jpg', focus: 'Güneş neden önemlidir?', points: ['Yaşam kaynağı olan Güneş, Dünya’nın ısı ve ışık kaynağıdır.', 'Mevsimlerin oluşmasında, bitkilerin fotosentez yapmasında ve su döngüsünde etkilidir.', 'Canlılar için uygun sıcaklığın oluşmasını sağlar ve bunun gibi birçok olayda rol oynar.']},
  {id: '02', title: 'Güneş’in Enerjisi ve Katmanları', image: 'gunes_1.jpg', focus: 'Güneş’in yapısı', points: ['Gaz hâlinde olan, küre biçimindeki Güneş’in enerjisini yapısındaki hidrojen atomları sağlar.', 'Güneş katmanlardan oluşur. Merkezinin sıcaklığı yaklaşık 15 milyon derece Celsius, yüzey sıcaklığı yaklaşık 5500 derece Celsius’tur.', 'Her saniye milyonlarca ton hidrojen atomu helyum atomlarına dönüşür ve Güneş’in enerjisini oluşturur.']},
  {id: '03', title: 'Güneş Lekeleri ve Dönüşü', image: 'gunes_1.jpg', focus: 'Güneş’in hareketi', points: ['Güneş’in enerjisi sonsuz değildir. Güneş, ömrünün yaklaşık yarısını tamamlamıştır.', 'Kalan ömrünün 4-5 milyar yıl olduğu düşünülmektedir.', 'Güneş lekeleri takip edilerek Güneş’in dönme yönü bulunabilir mi? Bu soruyu düşünelim.']},
  {id: '04', title: 'Güneş, Dünya ve Ay', image: 'gunes_2.jpg', focus: 'Büyüklükleri karşılaştıralım', points: ['Güneş, Dünya’dan yaklaşık 150 milyon kilometre uzaklıktadır.', 'Güneş sistemindeki tek yıldız olan Güneş, orta büyüklükte bir yıldızdır.', 'Güneş’te patlamalar olmasına rağmen bu patlamaların sesini duyamayız; çünkü ses boşlukta yayılmaz.']},
  {id: '05', title: 'Büyüklük ve Dönüş Yönü', image: 'gunes_2.jpg', focus: 'Güneş, Dünya ve Ay’ın özellikleri', points: ['Güneş’in yüzeyindeki soğuk bölgelere güneş lekesi denir.', 'Güneş, Dünya ile karşılaştırıldığında Dünya’nın kütlesinin 332 000, yüzey alanının 11 900, çekim kuvvetinin 28 katıdır.', 'Güneş’in kendi etrafında dönüş yönü batıdan doğuya, yani saat yönünün tersinedir.']},
  {id: '06', title: 'Şekil ve Uzaklık', image: 'gunes_2.jpg', focus: 'Gök cisimlerini nasıl görürüz?', points: ['Dünya, Ay’dan daha büyüktür. Dünya’nın çapı Ay’ın çapının yaklaşık 4 katıdır.', 'Güneş’in çapı ise Dünya’nın çapının 109 katıdır. Güneş, Dünya ve Ay’ı büyüklüklerine göre Güneş, Dünya, Ay şeklinde sıralayabiliriz.', 'Uzaklaştıkça cisimler gerçek boyutlarından daha küçük görünür.']},
  {id: '07', title: 'Uzaklık Algımızdan Örnekler', image: 'gunes_2.jpg', focus: 'Günlük hayattan kanıtlar', points: ['Çok uzaktaki ağaçların yakınımızdaki ağaçlardan daha küçük görünmesi buna örnektir.', 'Uçak yerden yükseldikçe uçağın içindeki yolcuların, evlerin ve taşıtların daha küçük görünmesi de uzaklıkla ilgilidir.', 'Camdan dışarı baktığımızda uzaktaki bir arabayı, yakındaki bir arabadan daha küçük görürüz.']},
  {id: '08', title: 'Gök Bilimi ve Astronom', image: 'gunes_3.jpg', focus: 'Gökyüzünü inceleyen bilim', points: ['İnsanlar geçmişten bu yana merakla gökyüzünü inceleyerek Güneş, Dünya ve Ay ile ilgili çeşitli fikirler ortaya atmışlardır.', 'Eskiden bazı insanlar Dünya’nın düz bir tepsi, bazen öküzün boynunda duran bir cisim, hatta yıldız, Ay ve Güneş gibi gök cisimlerinin gökyüzünde asılı olduğunu düşünüyordu.', 'Teleskobun icadıyla gökyüzü ve gök cisimleriyle ilgili masal ve hikâyelerin yerini gerçek gözlemler almıştır.']},
  {id: '09', title: 'Gök Cisimlerini Araştırmak', image: 'gunes_3.jpg', focus: 'Bilimsel gözlem', points: ['Bilim insanları uzay ve gök cisimlerinin gizemini çözmek için gözlemevleri kurmuş, uydular aracılığıyla çekilen fotoğraflarla Güneş, Dünya ve Ay’ın şekil ve büyüklükleri hakkında bilgi edinmişlerdir.', 'Dünya, kutuplardan biraz basık, Ekvator bölgesinde ise daha şişkin, küresel bir şekle sahiptir. Bu özel şekle geoit denir.', 'Dünya gibi Güneş ve Ay da küresel şekildedir.']},
  {id: '10', title: 'Gök Bilimi ve Gök Bilimci', image: 'gunes_3.jpg', focus: 'Kavramları öğrenelim', points: ['Dünya’nın küresel şekle sahip olduğunu gösteren kanıtlardan biri, kıyıdan uzaklaşan bir geminin önce gövdesinin, sonra bacasının, daha sonra dumanının gözden kaybolmasıdır.', 'Sürekli aynı yükseklikten aynı yöne doğru uçan uçağın ilk kalktığı yere tekrar gelmesi de bir kanıttır.', 'Gök cisimlerinin kökenlerini, fiziksel ve kimyasal yapılarını ve oluşum süreçlerini açıklayan bilim dalına gök bilimi, yani astronomi denir. Bu bilimle ilgilenen bilim insanına gök bilimci, yani astronom denir.']},
  {id: '11', title: 'Tebrikler!', image: 'gunes_3.jpg', focus: 'Dersi tamamladın', points: ['Güneş’in yaşamımızdaki önemini ve enerjisinin nasıl oluştuğunu öğrendin.', 'Güneş, Dünya ve Ay’ın büyüklüklerini, şekillerini ve uzaklık algısını öğrendin.', 'Gök bilimi ile astronom arasındaki farkı artık açıklayabilirsin.']},
].map((scene) => ({...scene, firstSpeaker: ['02', '04', '06', '08', '10'].includes(scene.id) ? 'ibrahim' as const : 'filiz' as const, splitSec: timings[scene.id].split_sec, totalSec: timings[scene.id].total_sec, visualKind: scene.id === '01' ? 'energy' : scene.id === '02' ? 'layers' : scene.id === '03' ? 'sun' : scene.id === '04' || scene.id === '05' ? 'solar-system' : scene.id === '06' || scene.id === '07' ? 'distance' : scene.id === '08' || scene.id === '09' || scene.id === '10' ? 'none' : 'final'}));

const AnimatedVisual: React.FC<{kind: string}> = ({kind}) => {
  const frame = useCurrentFrame();
  const rotation = frame * 1.4;
  const pulse = 1 + Math.sin(frame / 12) * 0.04;
  if (kind === 'energy') return <svg viewBox="0 0 260 250" width="260" height="250"><circle cx="130" cy="103" r="42" fill="#F59E0B" transform={`scale(${pulse})`} transformOrigin="130px 103px"/><g stroke="#FBBF24" strokeWidth="5" strokeLinecap="round" opacity="0.9"><path d="M130 43 V24"/><path d="M130 163 V182"/><path d="M70 103 H51"/><path d="M190 103 H209"/><path d="M88 61 L74 47"/><path d="M172 61 L186 47"/></g><path d="M130 171 C116 190 113 207 130 218 C147 207 144 190 130 171Z" fill="#38BDF8" opacity="0.85"/><path d="M130 177 C125 191 125 201 130 207 C135 201 135 191 130 177Z" fill="#BAE6FD"/><rect x="43" y="222" width="174" height="24" rx="6" fill="#FFFFFF"/><text x="130" y="239" textAnchor="middle" fill="#000000" stroke="#FFFFFF" strokeWidth="2" paintOrder="stroke" fontSize="14" fontWeight="bold">Isı, ışık ve yaşam</text></svg>;
  if (kind === 'layers') return <svg viewBox="0 0 260 250" width="260" height="250"><circle cx="130" cy="112" r="71" fill="none" stroke="#FDE68A" strokeWidth="4" strokeDasharray="6 5" transform={`rotate(${rotation} 130 112)`}/><circle cx="130" cy="112" r="55" fill="#F97316" opacity="0.28"/><circle cx="130" cy="112" r="39" fill="#F59E0B"/><circle cx="130" cy="112" r="21" fill="#FDE68A"/><path d="M130 58 V39 M130 165 V184" stroke="#38BDF8" strokeWidth="4" strokeLinecap="round"/><rect x="52" y="198" width="156" height="44" rx="6" fill="#FFFFFF"/><text x="130" y="215" textAnchor="middle" fill="#000000" stroke="#FFFFFF" strokeWidth="2" paintOrder="stroke" fontSize="14" fontWeight="bold">Katmanlı yapı</text><text x="130" y="234" textAnchor="middle" fill="#000000" stroke="#FFFFFF" strokeWidth="1" paintOrder="stroke" fontSize="12">Hidrojen → Helyum</text></svg>;
  if (kind === 'solar-system') return <svg viewBox="0 0 260 250" width="260" height="250"><circle cx="130" cy="125" r="94" fill="none" stroke="#FDE68A" strokeWidth="2" strokeDasharray="5 7"/><circle cx="130" cy="125" r="34" fill="#F97316" opacity="0.22"/><circle cx="130" cy="125" r="25" fill="#F59E0B" transform={`scale(${pulse})`} transformOrigin="130px 125px"/><g transform={`rotate(${rotation} 130 125)`}><circle cx="130" cy="31" r="13" fill="#2563EB"/><circle cx="130" cy="31" r="4" fill="#65A30D"/><circle cx="130" cy="31" r="24" fill="none" stroke="#93C5FD" strokeWidth="1.5" strokeDasharray="3 4"/><g transform={`rotate(${rotation * 3} 130 31)`}><circle cx="154" cy="31" r="5" fill="#D6D3D1"/></g></g><rect x="43" y="163" width="174" height="24" rx="6" fill="#FFFFFF"/><text x="130" y="180" textAnchor="middle" fill="#000000" stroke="#FFFFFF" strokeWidth="2" paintOrder="stroke" fontSize="14" fontWeight="bold">Güneş - Dünya - Ay</text></svg>;
  if (kind === 'distance') return <svg viewBox="0 0 260 250" width="260" height="250"><circle cx="52" cy="126" r="37" fill="#F59E0B" transform={`scale(${pulse})`} transformOrigin="52px 126px"/><circle cx="174" cy="126" r="25" fill="#2563EB"/><path d="M94 126 H140" stroke="#9A3412" strokeWidth="3" strokeDasharray="7 6"/><path d="M100 118 L92 126 L100 134 M134 118 L142 126 L134 134" fill="none" stroke="#9A3412" strokeWidth="3"/><rect x="25" y="174" width="210" height="56" rx="6" fill="#FFFFFF"/><text x="52" y="188" textAnchor="middle" fill="#000000" stroke="#FFFFFF" strokeWidth="2" paintOrder="stroke" fontSize="13" fontWeight="bold">Güneş</text><text x="174" y="188" textAnchor="middle" fill="#000000" stroke="#FFFFFF" strokeWidth="2" paintOrder="stroke" fontSize="13" fontWeight="bold">Dünya</text><text x="130" y="221" textAnchor="middle" fill="#000000" stroke="#FFFFFF" strokeWidth="2" paintOrder="stroke" fontSize="13" fontWeight="bold">Uzaklık görünüşü etkiler</text></svg>;
  if (kind === 'observation') return null;
  if (kind === 'final') return <svg viewBox="0 0 260 250" width="260" height="250"><circle cx="130" cy="112" r="66" fill="#FEF3C7" stroke="#D97706" strokeWidth="4"/><path d="M130 64 L143 91 L173 95 L151 116 L157 146 L130 132 L103 146 L109 116 L87 95 L117 91Z" fill="#F59E0B" transform={`rotate(${Math.sin(frame / 16) * 4} 130 112)`}/><path d="M108 112 L124 128 L153 94" fill="none" stroke="#FFFFFF" strokeWidth="8" strokeLinecap="round" strokeLinejoin="round"/><rect x="39" y="187" width="182" height="51" rx="6" fill="#FFFFFF"/><text x="130" y="204" textAnchor="middle" fill="#000000" stroke="#FFFFFF" strokeWidth="2" paintOrder="stroke" fontSize="16" fontWeight="bold">Dersi tamamladın</text><text x="130" y="225" textAnchor="middle" fill="#000000" stroke="#FFFFFF" strokeWidth="1" paintOrder="stroke" fontSize="12">Güneş sistemini öğrendin</text></svg>;
  return <svg viewBox="0 0 260 250" width="260" height="250"><circle cx="130" cy="118" r="56" fill="#F97316" opacity="0.25"/><circle cx="130" cy="118" r="42" fill="#F59E0B" transform={`scale(${pulse})`} transformOrigin="130px 118px"/><g fill="#000000" opacity="0.85"><circle cx="112" cy="98" r="6"/><circle cx="148" cy="135" r="5"/><circle cx="135" cy="88" r="4"/></g><path d="M130 38 V22 M130 198 V214 M50 118 H34 M210 118 H226" stroke="#EA580C" strokeWidth="5" strokeLinecap="round"/><rect x="47" y="207" width="166" height="24" rx="6" fill="#FFFFFF"/><text x="130" y="224" textAnchor="middle" fill="#000000" stroke="#FFFFFF" strokeWidth="2" paintOrder="stroke" fontSize="14" fontWeight="bold">Güneş ve güneş lekeleri</text></svg>;
};

const Scene: React.FC<{scene: Scene}> = ({scene}) => {
  const frame = useCurrentFrame();
  const {fps} = useVideoConfig();
  const splitFrame = Math.round(scene.splitSec * fps);
  const firstActive = frame < splitFrame;
  const entrance = spring({frame, fps, config: {damping: 16, stiffness: 100}});
  const filizTalking = scene.firstSpeaker === 'filiz' ? firstActive : !firstActive;
  const ibrahimTalking = scene.firstSpeaker === 'ibrahim' ? firstActive : !firstActive;
  const imageScale = interpolate(frame, [0, scene.totalSec * fps], [1.03, 1.08], {extrapolateRight: 'clamp'});
  return <AbsoluteFill style={{background: '#F8F1DE', overflow: 'hidden', fontFamily: 'Trebuchet MS, sans-serif'}}>
    <div style={{height: 76, background: '#9A3412', color: '#FFF7ED', display: 'flex', alignItems: 'center', justifyContent: 'space-between', padding: '0 30px', fontWeight: 900, zIndex: 5}}><span style={{fontSize: 20}}>5. SINIF FEN BİLGİSİ</span><span style={{fontSize: 24}}>{scene.title}</span></div>
    <div style={{position: 'absolute', inset: '92px 22px 18px', borderRadius: 20, overflow: 'hidden', background: '#FFFDF7', boxShadow: '0 8px 24px rgba(154,52,18,0.18)'}}><Img src={staticFile(`pages/fen/gunes/${scene.image}`)} style={{width: '100%', height: '100%', objectFit: 'cover', objectPosition: scene.image === 'gunes_1.jpg' ? 'center 34%' : scene.image === 'gunes_2.jpg' ? 'center 22%' : 'center 30%', transform: `scale(${imageScale})`, opacity: 0.2}}/><div style={{position: 'absolute', inset: 0, background: 'linear-gradient(90deg, rgba(255,253,247,0.98) 0%, rgba(255,253,247,0.91) 68%, rgba(255,253,247,0.6) 100%)'}}/></div>
    <div style={{position: 'absolute', left: 205, right: 250, top: 104, bottom: 74, display: 'flex', alignItems: 'flex-start', justifyContent: 'flex-start', zIndex: 2}}><div style={{width: 338, transform: `translateY(${(1 - entrance) * 20}px) scale(${0.97 + entrance * 0.03})`, background: 'rgba(255,255,255,0.97)', border: '3px solid #EA580C', borderRadius: 16, padding: '14px 16px', boxShadow: '0 12px 28px rgba(124,45,18,0.14)'}}><div style={{fontSize: 21, fontWeight: 900, color: '#9A3412', marginBottom: 9}}>{scene.focus}</div><div style={{display: 'grid', gap: 6}}>{scene.points.map((point, index) => <div key={point} style={{fontSize: scene.id === '05' || scene.id === '10' ? 12 : scene.id === '08' || scene.id === '09' ? 13 : 14, lineHeight: 1.28, fontWeight: 800, color: '#3F3F46', background: index % 2 === 0 ? '#FFF7ED' : '#FEF3C7', borderLeft: `5px solid ${index % 2 === 0 ? '#EA580C' : '#EAB308'}`, padding: '6px 7px'}}>{point}</div>)}</div></div></div>
    {scene.visualKind !== 'none' && <div style={{position: 'absolute', right: 258, top: 382, width: 192, height: 118, display: 'flex', alignItems: 'center', justifyContent: 'center', background: '#000000', border: '2px solid #B45309', borderRadius: 14, boxShadow: '0 8px 20px rgba(124,45,18,0.22)', zIndex: 1}}><AnimatedVisual kind={scene.visualKind}/></div>}
    <Minecraftfiliz x={112} y={150} scale={0.78} isTalking={filizTalking}/><Minecraftibrahim x={848} y={150} scale={0.78} flip isTalking={ibrahimTalking}/>
    <div style={{position: 'absolute', left: 57, top: 394, minWidth: 110, textAlign: 'center', background: filizTalking ? '#9A3412' : '#334155', color: '#FFFFFF', padding: '6px 12px', borderRadius: 9, border: '2px solid #FFFFFF', fontWeight: 900, zIndex: 10}}>Filiz</div><div style={{position: 'absolute', right: 57, top: 394, minWidth: 110, textAlign: 'center', background: ibrahimTalking ? '#B45309' : '#334155', color: '#FFFFFF', padding: '6px 12px', borderRadius: 9, border: '2px solid #FFFFFF', fontWeight: 900, zIndex: 10}}>İbrahim</div>
    <Audio src={staticFile(`audio/fen/gunes/${scene.id}_1.mp3`)}/><Sequence from={splitFrame}><Audio src={staticFile(`audio/fen/gunes/${scene.id}_2.mp3`)}/></Sequence>
  </AbsoluteFill>;
};

export const Gunes: React.FC = () => <AbsoluteFill>{sceneTexts.map((scene, index) => <Sequence key={scene.id} from={Math.round(sceneTexts.slice(0, index).reduce((sum, previous) => sum + previous.totalSec, 0) * 30)} durationInFrames={Math.round(scene.totalSec * 30)}><Scene scene={scene}/></Sequence>)}</AbsoluteFill>;
export const GunesConfig = {id: 'Gunes', fps: 30, width: 960, height: 540, durationInFrames: Math.round(sceneTexts.reduce((sum, scene) => sum + scene.totalSec, 0) * 30)};