import React from 'react';
import {AbsoluteFill, Audio, Img, Sequence, interpolate, spring, staticFile, useCurrentFrame, useVideoConfig} from 'remotion';
import {Minecraftfiliz, Minecraftibrahim} from '../MinecraftCharacter';
import timings from './isin_timings.json';

type Scene = {id: string; title: string; focus: string; points: string[]; speaker: 'filiz' | 'ibrahim'; audioSec: number; totalSec: number; visualKind: string};

const C = {navy: '#173B67', blue: '#1677C8', cyan: '#22D3EE', purple: '#7C3AED', pink: '#F43F5E', yellow: '#FBBF24', green: '#10B981', ink: '#182235'};

const scenes: Scene[] = [
  {id: '01', title: 'Işınla Sonsuz Yolculuk', focus: 'Bir noktadan sonsuza giden yol', points: ['Bir başlangıç noktası vardır.', 'Tek bir yönde uzanır.', 'Sonsuza kadar devam eder.'], speaker: 'filiz', audioSec: timings['01'].audio_sec, totalSec: timings['01'].total_sec, visualKind: 'intro'},
  {id: '02', title: 'Işının Özellikleri', focus: 'Başlangıç + yön + sonsuzluk', points: ['Başladığı nokta bellidir.', 'Düz bir çizgi üzerinde ilerler.', 'Ok işareti uzama yönünü gösterir.'], speaker: 'ibrahim', audioSec: timings['02'].audio_sec, totalSec: timings['02'].total_sec, visualKind: 'properties'},
  {id: '03', title: 'Işını Adlandıralım', focus: 'Önce başlangıç noktası', points: ['Başlangıç noktası A’dır.', 'Işın, B noktasından geçer.', 'Bu ışının adı A B ışınıdır: [AB'], speaker: 'filiz', audioSec: timings['03'].audio_sec, totalSec: timings['03'].total_sec, visualKind: 'naming'},
  {id: '04', title: 'Işınlardan Açılara', focus: 'İki ışın buluşursa', points: ['Aynı noktadan iki ışın çıkar.', 'Ortak nokta açının köşesidir.', 'Işınlar açının kollarını oluşturur.'], speaker: 'ibrahim', audioSec: timings['04'].audio_sec, totalSec: timings['04'].total_sec, visualKind: 'angle'},
  {id: '05', title: 'Işın Günlük Hayatta', focus: 'El fenerinin ışığı', points: ['Işık bir kaynaktan çıkar.', 'Seçilen yönde ilerler.', 'Işını hatırlatan güzel bir örnektir.'], speaker: 'filiz', audioSec: timings['05'].audio_sec, totalSec: timings['05'].total_sec, visualKind: 'rocket'},
  {id: '06', title: 'Kendi Işınlarımızı Çizelim', focus: 'Kareli zeminde üç ışın', points: ['Önce başlangıç noktasını seç.', 'Farklı yönlerde oklar çiz.', 'Başlangıç harfini önce yazarak adlandır.'], speaker: 'ibrahim', audioSec: timings['06'].audio_sec, totalSec: timings['06'].total_sec, visualKind: 'grid'},
  {id: '07', title: 'Tebrikler!', focus: 'Işını öğrendin', points: ['Bir noktadan başlar.', 'Tek yönde sonsuza uzanır.', 'Açıların kollarını oluşturur.'], speaker: 'filiz', audioSec: timings['07'].audio_sec, totalSec: timings['07'].total_sec, visualKind: 'final'},
];

const Sparkles = () => {
  const frame = useCurrentFrame();
  return <>{Array.from({length: 18}, (_, i) => {const x = (i * 137 + frame * (0.18 + (i % 3) * 0.05)) % 960; const y = 88 + ((i * 83 + Math.sin((frame + i * 11) / 18) * 22) % 420); const size = 3 + (i % 4); return <div key={i} style={{position: 'absolute', left: x, top: y, width: size, height: size, borderRadius: '50%', background: i % 2 ? C.cyan : C.yellow, opacity: 0.18 + (i % 3) * 0.08, zIndex: 1}}/>;})}</>;
};

const RayVisual: React.FC<{kind: string}> = ({kind}) => {
  const frame = useCurrentFrame();
  const {fps} = useVideoConfig();
  const enter = spring({frame, fps, config: {damping: 14, stiffness: 80}});
  const dash = -frame * 1.8;
  const glow = 1 + Math.sin(frame / 9) * 0.06;

  if (kind === 'intro') return <svg viewBox="0 0 280 240" width="270" height="230"><circle cx="45" cy="112" r="10" fill={C.pink}/><path d="M48 112 H234" stroke={C.purple} strokeWidth="11" strokeLinecap="round" pathLength="1" strokeDasharray="1" strokeDashoffset={1 - enter}/><path d="M55 112 H235" stroke={C.cyan} strokeWidth="4" strokeDasharray="12 10" strokeDashoffset={dash}/><polygon points="230,96 260,112 230,128" fill={C.cyan} transform={`scale(${glow})`} transformOrigin="242px 112px"/><g fill={C.yellow}>{[[82,72],[132,145],[188,74],[226,162]].map(([x,y], i) => <text key={i} x={x} y={y} fontSize={17 + i % 2 * 4} transform={`rotate(${frame + i * 25} ${x} ${y})`}>✦</text>)}</g><text x="140" y="204" textAnchor="middle" fill={C.navy} fontSize="22" fontWeight="900">SONSUZA DOĞRU!</text></svg>;
  if (kind === 'properties') return <svg viewBox="0 0 280 240" width="270" height="230"><circle cx="44" cy="66" r="9" fill={C.pink}/><path d="M49 66 H238" stroke={C.blue} strokeWidth="8" strokeLinecap="round"/><polygon points="232,52 260,66 232,80" fill={C.blue}/><path d="M65 112 H245" stroke={C.cyan} strokeWidth="5" strokeDasharray="11 9" strokeDashoffset={dash}/><g fontSize="16" fontWeight="900"><rect x="30" y="142" width="220" height="27" rx="8" fill="#FFE4E6"/><text x="140" y="161" textAnchor="middle" fill={C.pink}>● BAŞLANGIÇ NOKTASI</text><rect x="30" y="178" width="220" height="27" rx="8" fill="#E0F2FE"/><text x="140" y="197" textAnchor="middle" fill={C.blue}>➜ TEK YÖNDE SONSUZ</text></g></svg>;
  if (kind === 'naming') return <svg viewBox="0 0 280 240" width="270" height="230"><circle cx="45" cy="92" r="9" fill={C.pink}/><circle cx="157" cy="92" r="8" fill={C.yellow}/><path d="M50 92 H238" stroke={C.purple} strokeWidth="8" strokeLinecap="round" pathLength="1" strokeDasharray="1" strokeDashoffset={1 - enter}/><polygon points="232,77 260,92 232,107" fill={C.cyan}/><text x="45" y="66" textAnchor="middle" fill={C.ink} fontSize="22" fontWeight="900">A</text><text x="157" y="66" textAnchor="middle" fill={C.ink} fontSize="22" fontWeight="900">B</text><rect x="66" y="145" width="148" height="52" rx="13" fill="#F3E8FF" stroke={C.purple} strokeWidth="3"/><text x="140" y="179" textAnchor="middle" fill={C.purple} fontSize="27" fontWeight="900">[AB IŞINI</text><text x="140" y="224" textAnchor="middle" fill={C.navy} fontSize="14" fontWeight="900">Önce başlangıç: A</text></svg>;
  if (kind === 'angle') {const rotation = -18 + Math.sin(frame / 20) * 16; return <svg viewBox="0 0 280 240" width="270" height="230"><g transform={`rotate(${rotation} 65 176)`}><path d="M65 176 L237 82" stroke={C.purple} strokeWidth="8" strokeLinecap="round"/><polygon points="224,75 255,72 239,99" fill={C.purple}/></g><path d="M65 176 H237" stroke={C.blue} strokeWidth="8" strokeLinecap="round"/><polygon points="230,161 260,176 230,191" fill={C.blue}/><circle cx="65" cy="176" r="11" fill={C.pink}/><path d="M105 176 A40 40 0 0 0 99 155" fill="none" stroke={C.yellow} strokeWidth="7"/><text x="65" y="213" textAnchor="middle" fill={C.ink} fontSize="15" fontWeight="900">KÖŞE</text><text x="180" y="218" textAnchor="middle" fill={C.navy} fontSize="19" fontWeight="900">İKİ IŞIN = AÇI</text></svg>;}
  if (kind === 'rocket') {const travel = (frame * 2.4) % 215; return <svg viewBox="0 0 280 240" width="270" height="230"><rect x="22" y="30" width="236" height="150" rx="18" fill="#172554"/><circle cx="48" cy="106" r="13" fill={C.yellow}/><path d="M55 106 H250" stroke={C.yellow} strokeWidth="9" opacity="0.35"/><path d="M55 106 H250" stroke="#FEF3C7" strokeWidth="4" strokeDasharray="10 8" strokeDashoffset={dash}/><g transform={`translate(${28 + travel} 106)`}><polygon points="0,-13 27,0 0,13" fill={C.cyan}/><circle cx="4" cy="0" r="4" fill="white"/><path d="M-2 -7 L-16 0 L-2 7" fill={C.pink}/></g><text x="140" y="213" textAnchor="middle" fill={C.navy} fontSize="18" fontWeight="900">IŞIK GİBİ İLERLE!</text></svg>;}
  if (kind === 'grid') return <svg viewBox="0 0 280 240" width="270" height="230"><g stroke="#C7D2FE" strokeWidth="1">{Array.from({length: 10}, (_, i) => <path key={`v${i}`} d={`M${25 + i * 25} 18 V205`}/>)}{Array.from({length: 8}, (_, i) => <path key={`h${i}`} d={`M25 ${18 + i * 25} H250`}/>)}</g><circle cx="125" cy="145" r="9" fill={C.pink}/><g strokeWidth="7" strokeLinecap="round" pathLength="1" strokeDasharray="1" strokeDashoffset={1 - enter}><path d="M125 145 L225 45" stroke={C.purple}/><path d="M125 145 L240 145" stroke={C.blue}/><path d="M125 145 L185 205" stroke={C.green}/></g><g><polygon points="214,42 240,30 228,56" fill={C.purple}/><polygon points="229,132 257,145 229,158" fill={C.blue}/><polygon points="176,199 199,218 190,190" fill={C.green}/></g><text x="112" y="170" fill={C.ink} fontSize="17" fontWeight="900">A</text></svg>;
  return <svg viewBox="0 0 280 240" width="270" height="230"><g>{Array.from({length: 22}, (_, i) => {const x = 24 + (i * 47) % 230; const y = 20 + (i * 73 + frame * (1 + i % 3)) % 145; return <rect key={i} x={x} y={y} width="7" height="15" rx="2" fill={[C.pink,C.cyan,C.yellow,C.green][i % 4]} transform={`rotate(${frame * 2 + i * 21} ${x} ${y})`}/>;})}</g><circle cx="140" cy="92" r="64" fill="#FEF3C7" stroke={C.yellow} strokeWidth="6"/><path d="M104 95 L130 121 L178 69" fill="none" stroke={C.green} strokeWidth="13" strokeLinecap="round" strokeLinejoin="round"/><text x="140" y="181" textAnchor="middle" fill={C.purple} fontSize="24" fontWeight="900">IŞIN USTASI!</text></svg>;
};

const SceneView: React.FC<{scene: Scene}> = ({scene}) => {
  const frame = useCurrentFrame();
  const {fps} = useVideoConfig();
  const talking = frame < Math.round(scene.audioSec * fps);
  const enter = spring({frame, fps, config: {damping: 13, stiffness: 95}});
  const imageScale = interpolate(frame, [0, scene.totalSec * fps], [1.02, 1.09], {extrapolateRight: 'clamp'});
  const filizTalking = scene.speaker === 'filiz' && talking;
  const ibrahimTalking = scene.speaker === 'ibrahim' && talking;
  const showCta = scene.id === '07' && frame >= Math.max(0, scene.totalSec * fps - 5 * fps);

  return <AbsoluteFill style={{background: 'linear-gradient(135deg, #E0F2FE 0%, #F5F3FF 55%, #FFF1F2 100%)', overflow: 'hidden', fontFamily: 'Trebuchet MS, Arial, sans-serif'}}>
    <Sparkles/>
    <div style={{height: 76, background: 'linear-gradient(90deg, #173B67, #5B21B6 58%, #BE123C)', color: 'white', display: 'flex', alignItems: 'center', justifyContent: 'space-between', padding: '0 30px', fontWeight: 900, position: 'relative', zIndex: 8}}><span style={{fontSize: 20}}>5. SINIF MATEMATİK</span><span style={{fontSize: 24}}>{scene.title}</span></div>
    <div style={{position: 'absolute', inset: '92px 22px 18px', borderRadius: 24, overflow: 'hidden', background: 'white', boxShadow: '0 12px 30px rgba(91,33,182,0.2)', zIndex: 1}}><Img src={staticFile('pages/matematik/4.ısın.jpg')} style={{width: '100%', height: '100%', objectFit: 'cover', objectPosition: 'center 43%', transform: `scale(${imageScale})`, opacity: 0.16}}/><div style={{position: 'absolute', inset: 0, background: 'linear-gradient(90deg, rgba(255,255,255,0.98) 0%, rgba(250,245,255,0.91) 66%, rgba(239,246,255,0.64) 100%)'}}/></div>
    <div style={{position: 'absolute', left: 205, top: 104, width: 370, zIndex: 3, transform: `translateY(${(1 - enter) * 28}px) rotate(${(1 - enter) * -2.5}deg) scale(${0.96 + enter * 0.04})`}}><div style={{background: 'rgba(255,255,255,0.97)', border: `3px solid ${scene.id === '04' ? C.purple : C.blue}`, borderRadius: 20, padding: '15px 17px', boxShadow: '0 12px 28px rgba(91,33,182,0.16)'}}><div style={{fontSize: 21, fontWeight: 900, color: C.navy, marginBottom: 9}}>{scene.focus}</div><div style={{display: 'grid', gap: 7}}>{scene.points.map((point, index) => <div key={point} style={{fontSize: 14, lineHeight: 1.28, fontWeight: 800, color: C.ink, background: ['#EFF6FF','#FFF1F2','#F5F3FF'][index], borderLeft: `5px solid ${[C.blue,C.pink,C.purple][index]}`, padding: '7px 8px', transform: `translateX(${Math.sin((frame + index * 12) / 18) * 1.5}px)`}}>{point}</div>)}</div></div></div>
    <div style={{position: 'absolute', right: 242, top: 294, width: 222, height: 204, display: 'flex', alignItems: 'center', justifyContent: 'center', background: 'rgba(255,255,255,0.97)', border: `3px solid ${C.purple}`, borderRadius: 20, boxShadow: '0 12px 25px rgba(91,33,182,0.2)', zIndex: 2, transform: `scale(${0.96 + Math.sin(frame / 15) * 0.008})`}}><RayVisual kind={scene.visualKind}/></div>
    <Minecraftfiliz x={112} y={150} scale={0.78} isTalking={filizTalking}/><Minecraftibrahim x={848} y={150} scale={0.78} flip isTalking={ibrahimTalking}/>
    <div style={{position: 'absolute', left: 57, top: 394, minWidth: 110, textAlign: 'center', background: filizTalking ? C.pink : '#334155', color: 'white', padding: '6px 12px', borderRadius: 10, border: '2px solid white', fontWeight: 900, zIndex: 10}}>Filiz</div><div style={{position: 'absolute', right: 57, top: 394, minWidth: 110, textAlign: 'center', background: ibrahimTalking ? C.purple : '#334155', color: 'white', padding: '6px 12px', borderRadius: 10, border: '2px solid white', fontWeight: 900, zIndex: 10}}>İbrahim</div>
    {showCta && <div style={{position: 'absolute', left: 255, right: 255, bottom: 28, display: 'flex', gap: 18, zIndex: 20}}><div style={{flex: 1, background: C.pink, color: 'white', padding: '13px 18px', borderRadius: 14, textAlign: 'center', fontSize: 23, fontWeight: 900, boxShadow: '0 7px 15px rgba(0,0,0,0.18)'}}>♥ BEĞEN</div><div style={{flex: 1, background: C.purple, color: 'white', padding: '13px 18px', borderRadius: 14, textAlign: 'center', fontSize: 21, fontWeight: 900, boxShadow: '0 7px 15px rgba(0,0,0,0.18)'}}>✓ ABONE OL</div></div>}
    <Audio src={staticFile(`audio/matematik/isin/${scene.id}.mp3`)}/>
  </AbsoluteFill>;
};

export const Isin: React.FC = () => <AbsoluteFill>{scenes.map((scene, index) => <Sequence key={scene.id} from={Math.round(scenes.slice(0, index).reduce((sum, previous) => sum + previous.totalSec, 0) * 30)} durationInFrames={Math.round(scene.totalSec * 30)}><SceneView scene={scene}/></Sequence>)}</AbsoluteFill>;

export const IsinConfig = {id: 'Isin', fps: 30, width: 960, height: 540, durationInFrames: Math.round(scenes.reduce((sum, scene) => sum + scene.totalSec, 0) * 30)};
