import React from 'react';
import {AbsoluteFill, Audio, Img, Sequence, interpolate, spring, staticFile, useCurrentFrame, useVideoConfig} from 'remotion';
import {Minecraftfiliz, Minecraftibrahim} from '../MinecraftCharacter';
import timings from './dogru_timings.json';

type Scene = {id: string; title: string; focus: string; points: string[]; speaker: 'filiz' | 'ibrahim'; audioSec: number; totalSec: number; visualKind: string};

const C = {navy: '#102A43', blue: '#0EA5E9', teal: '#14B8A6', green: '#10B981', orange: '#F97316', pink: '#EC4899', yellow: '#FBBF24', violet: '#7C3AED', ink: '#172033'};

const scenes: Scene[] = [
  {id: '01', title: 'Sonsuza Düz Bir Yolculuk', focus: 'İki yönde sonsuza uzanan doğru', points: ['Düz bir çizgidir.', 'Başlangıç ve bitiş noktası yoktur.', 'Her iki yönde sonsuza uzanır.'], speaker: 'filiz', audioSec: timings['01'].audio_sec, totalSec: timings['01'].total_sec, visualKind: 'intro'},
  {id: '02', title: 'Doğrunun Özellikleri', focus: 'Uç nokta yok, iki yön var', points: ['Doğrunun uç noktası bulunmaz.', 'İki ucundaki oklar uzama yönlerini gösterir.', 'Uzunluğu ölçülemez; çünkü sonsuzdur.'], speaker: 'ibrahim', audioSec: timings['02'].audio_sec, totalSec: timings['02'].total_sec, visualKind: 'properties'},
  {id: '03', title: 'İki Noktayla Adlandırma', focus: 'A ve B noktalarından geçen doğru', points: ['Doğru üzerindeki iki nokta seçilir.', 'Noktalar A ve B harfleriyle adlandırılır.', 'Çift yönlü ok, doğrunun iki yönde uzadığını gösterir.'], speaker: 'filiz', audioSec: timings['03'].audio_sec, totalSec: timings['03'].total_sec, visualKind: 'naming'},
  {id: '04', title: 'AB ile BA Aynı Doğrudur', focus: 'Noktaların sırası önemli değil', points: ['AB doğrusu iki yönde uzanır.', 'BA doğrusu da aynı çizgiyi gösterir.', 'Bu nedenle AB doğrusu = BA doğrusudur.'], speaker: 'ibrahim', audioSec: timings['04'].audio_sec, totalSec: timings['04'].total_sec, visualKind: 'order'},
  {id: '05', title: 'Küçük Harfle Adlandırma', focus: 'd doğrusu', points: ['Doğrular küçük harfle adlandırılabilir.', 'Harf doğrunun yanına yazılır.', 'Örnekteki AB doğrusu, d doğrusudur.'], speaker: 'filiz', audioSec: timings['05'].audio_sec, totalSec: timings['05'].total_sec, visualKind: 'letter'},
  {id: '06', title: 'Kendi Doğrularımızı Çizelim', focus: 'Kareli zeminde üç doğru', points: ['Önce iki farklı nokta seç.', 'Noktalardan geçen düz çizgiyi iki yöne uzat.', 'İki uca ok ekleyip doğruyu adlandır.'], speaker: 'ibrahim', audioSec: timings['06'].audio_sec, totalSec: timings['06'].total_sec, visualKind: 'grid'},
  {id: '07', title: 'Üç Kavramı Karşılaştıralım', focus: 'Doğru parçası, ışın ve doğru', points: ['Doğru parçası: İki uç noktası vardır.', 'Işın: Bir noktadan başlayıp tek yönde uzanır.', 'Doğru: İki yönde sonsuza uzanır.'], speaker: 'filiz', audioSec: timings['07'].audio_sec, totalSec: timings['07'].total_sec, visualKind: 'compare'},
  {id: '08', title: 'Tebrikler!', focus: 'Doğruyu öğrendin', points: ['Düzdür ve uç noktası yoktur.', 'İki yönde sonsuza uzanır.', 'İki noktayla veya küçük harfle adlandırılır.'], speaker: 'ibrahim', audioSec: timings['08'].audio_sec, totalSec: timings['08'].total_sec, visualKind: 'final'},
];

const Ambient = () => {
  const frame = useCurrentFrame();
  const blobs = [
    {x: 80, y: 120, size: 150, color: '#BAE6FD', speed: 37},
    {x: 690, y: 105, size: 185, color: '#CCFBF1', speed: 49},
    {x: 350, y: 390, size: 125, color: '#FFEDD5', speed: 41},
    {x: 790, y: 370, size: 145, color: '#EDE9FE', speed: 55},
  ];
  return <>{blobs.map((blob, i) => <div key={i} style={{position: 'absolute', left: blob.x + Math.sin((frame + i * 17) / blob.speed) * 22, top: blob.y + Math.cos((frame + i * 29) / blob.speed) * 16, width: blob.size, height: blob.size, borderRadius: '50%', background: blob.color, filter: 'blur(30px)', opacity: 0.46, zIndex: 0}}/>)}</>;
};

const ArrowHead: React.FC<{x: number; y: number; direction: 'left' | 'right'; color: string; pulse?: number}> = ({x, y, direction, color, pulse = 1}) => <polygon points={direction === 'left' ? `${x + 24},${y - 15} ${x - 5},${y} ${x + 24},${y + 15}` : `${x - 24},${y - 15} ${x + 5},${y} ${x - 24},${y + 15}`} fill={color} transform={`scale(${pulse})`} transformOrigin={`${x}px ${y}px`}/>;

const LineVisual: React.FC<{kind: string}> = ({kind}) => {
  const frame = useCurrentFrame();
  const {fps} = useVideoConfig();
  const enter = spring({frame, fps, config: {damping: 15, stiffness: 72}});
  const pulse = 1 + Math.sin(frame / 10) * 0.055;
  const dash = frame * 2.2;

  if (kind === 'intro') {const half = 91 * enter; return <svg viewBox="0 0 280 240" width="270" height="230"><defs><filter id="glow"><feGaussianBlur stdDeviation="4" result="b"/><feMerge><feMergeNode in="b"/><feMergeNode in="SourceGraphic"/></feMerge></filter></defs><path d={`M${140 - half} 108 H${140 + half}`} stroke={C.teal} strokeWidth="17" opacity="0.16" strokeLinecap="round"/><path d={`M${140 - half} 108 H${140 + half}`} stroke={C.blue} strokeWidth="8" strokeLinecap="round" filter="url(#glow)"/><path d={`M${140 - half} 108 H${140 + half}`} stroke="#FFFFFF" strokeWidth="2.5" strokeDasharray="10 10" strokeDashoffset={dash}/><ArrowHead x={37} y={108} direction="left" color={C.teal} pulse={pulse}/><ArrowHead x={243} y={108} direction="right" color={C.blue} pulse={pulse}/><g fill={C.yellow}>{[70,110,170,215].map((x, i) => <circle key={i} cx={x} cy={66 + Math.sin((frame + i * 12) / 10) * 8} r={3 + i % 2}/>)}</g><text x="140" y="184" textAnchor="middle" fill={C.navy} fontSize="25" fontWeight="900">← SONSUZ →</text><text x="140" y="214" textAnchor="middle" fill={C.ink} fontSize="15">Düz ve bitmeyen yolculuk</text></svg>;}
  if (kind === 'properties') return <svg viewBox="0 0 280 240" width="270" height="230"><ArrowHead x={31} y={69} direction="left" color={C.orange}/><path d="M42 69 H238" stroke={C.navy} strokeWidth="8" strokeLinecap="round"/><ArrowHead x={249} y={69} direction="right" color={C.teal}/><g>{Array.from({length: 7}, (_, i) => {const x = 55 + ((frame * (i % 2 ? 2 : -2) + i * 41 + 400) % 180); return <circle key={i} cx={x} cy="69" r="3.5" fill={i % 2 ? C.yellow : C.blue}/>;})}</g><rect x="28" y="118" width="224" height="34" rx="10" fill="#ECFDF5"/><text x="140" y="141" textAnchor="middle" fill={C.green} fontSize="17" fontWeight="900">✓ UÇ NOKTASI YOK</text><rect x="28" y="164" width="224" height="34" rx="10" fill="#EFF6FF"/><text x="140" y="187" textAnchor="middle" fill={C.blue} fontSize="17" fontWeight="900">⇆ İKİ YÖNDE SONSUZ</text><text x="32" y="93" fill={C.orange} fontSize="16" fontWeight="900">−∞</text><text x="229" y="93" fill={C.teal} fontSize="16" fontWeight="900">+∞</text></svg>;
  if (kind === 'naming') return <svg viewBox="0 0 280 240" width="270" height="230"><ArrowHead x={29} y={85} direction="left" color={C.orange}/><path d="M42 85 H238" stroke={C.blue} strokeWidth="7" strokeLinecap="round" pathLength="1" strokeDasharray="1" strokeDashoffset={1 - enter}/><ArrowHead x={251} y={85} direction="right" color={C.teal}/><circle cx="92" cy="85" r="8" fill={C.pink}/><circle cx="188" cy="85" r="8" fill={C.yellow}/><text x="92" y="59" textAnchor="middle" fill={C.ink} fontSize="22" fontWeight="900">A</text><text x="188" y="59" textAnchor="middle" fill={C.ink} fontSize="22" fontWeight="900">B</text><rect x="73" y="135" width="134" height="62" rx="16" fill="#E0F2FE" stroke={C.blue} strokeWidth="3"/><text x="140" y="158" textAnchor="middle" fill={C.blue} fontSize="26" fontWeight="900">↔</text><text x="140" y="187" textAnchor="middle" fill={C.navy} fontSize="24" fontWeight="900">AB DOĞRUSU</text><text x="140" y="224" textAnchor="middle" fill={C.ink} fontSize="14">A ve B’den geçer</text></svg>;
  if (kind === 'order') {const swap = (Math.sin(frame / 18) + 1) / 2; return <svg viewBox="0 0 280 240" width="270" height="230"><g transform={`translate(${swap * 8} 0) scale(${0.98 + swap * 0.02})`}><rect x="23" y="42" width="95" height="70" rx="16" fill="#E0F2FE" stroke={C.blue} strokeWidth="3"/><text x="70" y="69" textAnchor="middle" fill={C.blue} fontSize="22" fontWeight="900">↔</text><text x="70" y="99" textAnchor="middle" fill={C.navy} fontSize="26" fontWeight="900">AB</text></g><g transform={`translate(${-swap * 8} 0) scale(${1 - swap * 0.02})`}><rect x="162" y="42" width="95" height="70" rx="16" fill="#ECFDF5" stroke={C.teal} strokeWidth="3"/><text x="209" y="69" textAnchor="middle" fill={C.teal} fontSize="22" fontWeight="900">↔</text><text x="209" y="99" textAnchor="middle" fill={C.navy} fontSize="26" fontWeight="900">BA</text></g><text x="140" y="96" textAnchor="middle" fill={C.orange} fontSize="34" fontWeight="900">=</text><path d="M35 160 H245" stroke={C.violet} strokeWidth="8"/><ArrowHead x={24} y={160} direction="left" color={C.orange}/><ArrowHead x={256} y={160} direction="right" color={C.teal}/><text x="140" y="213" textAnchor="middle" fill={C.navy} fontSize="19" fontWeight="900">AYNI DOĞRU</text></svg>;}
  if (kind === 'letter') return <svg viewBox="0 0 280 240" width="270" height="230"><g transform={`rotate(${Math.sin(frame / 25) * 3} 140 98)`}><ArrowHead x={29} y={98} direction="left" color={C.orange}/><path d="M42 98 H238" stroke={C.teal} strokeWidth="8" strokeLinecap="round"/><ArrowHead x={251} y={98} direction="right" color={C.blue}/><circle cx="94" cy="98" r="7" fill={C.pink}/><circle cx="188" cy="98" r="7" fill={C.yellow}/><text x="94" y="72" textAnchor="middle" fill={C.ink} fontSize="19" fontWeight="900">A</text><text x="188" y="72" textAnchor="middle" fill={C.ink} fontSize="19" fontWeight="900">B</text></g><circle cx="140" cy="167" r="37" fill="#FFF7ED" stroke={C.orange} strokeWidth="4" transform={`scale(${pulse})`} transformOrigin="140px 167px"/><text x="140" y="181" textAnchor="middle" fill={C.orange} fontSize="48" fontWeight="900" fontStyle="italic">d</text><text x="140" y="226" textAnchor="middle" fill={C.navy} fontSize="18" fontWeight="900">d DOĞRUSU</text></svg>;
  if (kind === 'grid') return <svg viewBox="0 0 280 240" width="270" height="230"><g stroke="#CBD5E1" strokeWidth="1">{Array.from({length: 11}, (_, i) => <path key={`v${i}`} d={`M${18 + i * 25} 17 V222`}/>)}{Array.from({length: 9}, (_, i) => <path key={`h${i}`} d={`M18 ${17 + i * 25} H268`}/>)}</g><g strokeWidth="6" strokeLinecap="round" pathLength="1" strokeDasharray="1" strokeDashoffset={1 - enter}><path d="M35 190 L245 48" stroke={C.violet}/><path d="M28 120 H255" stroke={C.blue}/><path d="M58 34 L230 212" stroke={C.green}/></g><g><g transform="rotate(-34 25 197)"><ArrowHead x={25} y={197} direction="left" color={C.violet}/></g><g transform="rotate(-34 255 41)"><ArrowHead x={255} y={41} direction="right" color={C.violet}/></g><ArrowHead x={18} y={120} direction="left" color={C.orange}/><ArrowHead x={265} y={120} direction="right" color={C.blue}/><g transform="rotate(46 50 26)"><ArrowHead x={50} y={26} direction="left" color={C.green}/></g><g transform="rotate(46 238 220)"><ArrowHead x={238} y={220} direction="right" color={C.green}/></g></g><g fill={C.pink}>{[[85,156],[170,99],[105,120],[205,120],[97,74],[188,169]].map(([x,y], i) => <circle key={i} cx={x} cy={y} r="5"/>)}</g></svg>;
  if (kind === 'compare') return <svg viewBox="0 0 280 240" width="270" height="230"><g fontSize="13" fontWeight="900" fill={C.navy}><text x="12" y="46">PARÇA</text><text x="12" y="113">IŞIN</text><text x="12" y="180">DOĞRU</text></g><g><circle cx="90" cy="40" r="7" fill={C.pink}/><path d="M97 40 H225" stroke={C.orange} strokeWidth="7"/><circle cx="232" cy="40" r="7" fill={C.pink}/><circle cx="90" cy="107" r="7" fill={C.pink}/><path d="M97 107 H228" stroke={C.violet} strokeWidth="7"/><ArrowHead x={244} y={107} direction="right" color={C.violet}/><ArrowHead x={80} y={174} direction="left" color={C.orange}/><path d="M93 174 H228" stroke={C.blue} strokeWidth="7"/><ArrowHead x={244} y={174} direction="right" color={C.teal}/></g><g fontSize="12" fill={C.ink}><text x="140" y="64" textAnchor="middle">iki uç nokta</text><text x="153" y="131" textAnchor="middle">bir başlangıç</text><text x="158" y="202" textAnchor="middle">iki yönde sonsuz</text></g><rect x="68" y="216" width="185" height="20" rx="7" fill="#ECFDF5"/><text x="160" y="231" textAnchor="middle" fill={C.green} fontSize="12" fontWeight="900">OK SAYISINA DİKKAT ET!</text></svg>;
  return <svg viewBox="0 0 280 240" width="270" height="230"><g>{Array.from({length: 25}, (_, i) => {const x = 18 + (i * 53) % 250; const y = 12 + (i * 71 + frame * (1 + i % 3)) % 155; return <rect key={i} x={x} y={y} width="7" height="15" rx="2" fill={[C.orange,C.blue,C.yellow,C.green,C.pink][i % 5]} transform={`rotate(${frame * 2 + i * 19} ${x} ${y})`}/>;})}</g><path d="M62 102 C78 45 124 46 140 102 C156 158 202 159 218 102 C202 45 156 46 140 102 C124 158 78 159 62 102Z" fill="none" stroke={C.teal} strokeWidth="10" transform={`scale(${pulse})`} transformOrigin="140px 102px"/><text x="140" y="195" textAnchor="middle" fill={C.navy} fontSize="25" fontWeight="900">DOĞRU USTASI!</text><text x="140" y="224" textAnchor="middle" fill={C.green} fontSize="15" fontWeight="900">İki yönde sonsuz</text></svg>;
};

const SceneView: React.FC<{scene: Scene}> = ({scene}) => {
  const frame = useCurrentFrame();
  const {fps} = useVideoConfig();
  const totalFrames = Math.round(scene.totalSec * fps);
  const fade = interpolate(frame, [0, 9, Math.max(10, totalFrames - 9), totalFrames], [0, 1, 1, 0], {extrapolateLeft: 'clamp', extrapolateRight: 'clamp'});
  const talking = frame < Math.round(scene.audioSec * fps);
  const enter = spring({frame, fps, config: {damping: 14, stiffness: 95}});
  const imageScale = interpolate(frame, [0, totalFrames], [1.02, 1.09], {extrapolateRight: 'clamp'});
  const filizTalking = scene.speaker === 'filiz' && talking;
  const ibrahimTalking = scene.speaker === 'ibrahim' && talking;
  const showCta = scene.id === '08' && frame >= Math.max(0, totalFrames - 5 * fps);

  return <AbsoluteFill style={{opacity: fade, background: 'linear-gradient(135deg, #E0F2FE 0%, #ECFDF5 48%, #FFF7ED 100%)', overflow: 'hidden', fontFamily: 'Trebuchet MS, Arial, sans-serif'}}>
    <Ambient/>
    <div style={{height: 76, background: 'linear-gradient(90deg, #102A43, #0369A1 52%, #0F766E)', color: 'white', display: 'flex', alignItems: 'center', justifyContent: 'space-between', padding: '0 30px', fontWeight: 900, position: 'relative', zIndex: 9}}><span style={{fontSize: 20}}>5. SINIF MATEMATİK</span><span style={{fontSize: 24}}>{scene.title}</span></div>
    <div style={{position: 'absolute', inset: '92px 22px 18px', borderRadius: 25, overflow: 'hidden', background: 'white', boxShadow: '0 14px 34px rgba(15,118,110,0.2)', zIndex: 1}}><Img src={staticFile('pages/matematik/5.dogru.jpg')} style={{width: '100%', height: '100%', objectFit: 'cover', objectPosition: 'center 42%', transform: `scale(${imageScale})`, opacity: 0.15}}/><div style={{position: 'absolute', inset: 0, background: 'linear-gradient(90deg, rgba(255,255,255,0.98) 0%, rgba(245,253,252,0.91) 67%, rgba(239,246,255,0.65) 100%)'}}/></div>
    <div style={{position: 'absolute', left: 205, top: 104, width: 370, zIndex: 4, transform: `translateY(${(1 - enter) * 30}px) rotate(${(1 - enter) * -2}deg) scale(${0.96 + enter * 0.04})`}}><div style={{background: 'rgba(255,255,255,0.97)', border: `3px solid ${scene.id === '04' ? C.orange : C.teal}`, borderRadius: 20, padding: '15px 17px', boxShadow: '0 13px 29px rgba(16,42,67,0.16)'}}><div style={{fontSize: 21, fontWeight: 900, color: C.navy, marginBottom: 9}}>{scene.focus}</div><div style={{display: 'grid', gap: 7}}>{scene.points.map((point, index) => <div key={point} style={{fontSize: 14, lineHeight: 1.28, fontWeight: 800, color: C.ink, background: ['#EFF6FF','#ECFDF5','#FFF7ED'][index], borderLeft: `5px solid ${[C.blue,C.teal,C.orange][index]}`, padding: '7px 8px', transform: `translateX(${Math.sin((frame + index * 13) / 19) * 1.4}px)`}}>{point}</div>)}</div></div></div>
    <div style={{position: 'absolute', right: 242, top: 294, width: 222, height: 204, display: 'flex', alignItems: 'center', justifyContent: 'center', background: 'rgba(255,255,255,0.97)', border: `3px solid ${C.teal}`, borderRadius: 21, boxShadow: '0 13px 28px rgba(14,165,233,0.18)', zIndex: 3, transform: `translateY(${Math.sin(frame / 18) * 2}px) scale(${0.97 + Math.sin(frame / 15) * 0.008})`}}><LineVisual kind={scene.visualKind}/></div>
    <Minecraftfiliz x={112} y={150} scale={0.78} isTalking={filizTalking}/><Minecraftibrahim x={848} y={150} scale={0.78} flip isTalking={ibrahimTalking}/>
    <div style={{position: 'absolute', left: 57, top: 394, minWidth: 110, textAlign: 'center', background: filizTalking ? C.orange : '#334155', color: 'white', padding: '6px 12px', borderRadius: 10, border: '2px solid white', fontWeight: 900, zIndex: 10}}>Filiz</div><div style={{position: 'absolute', right: 57, top: 394, minWidth: 110, textAlign: 'center', background: ibrahimTalking ? C.teal : '#334155', color: 'white', padding: '6px 12px', borderRadius: 10, border: '2px solid white', fontWeight: 900, zIndex: 10}}>İbrahim</div>
    {showCta && <div style={{position: 'absolute', left: 255, right: 255, bottom: 28, display: 'flex', gap: 18, zIndex: 20}}><div style={{flex: 1, background: C.orange, color: 'white', padding: '13px 18px', borderRadius: 14, textAlign: 'center', fontSize: 23, fontWeight: 900, boxShadow: '0 7px 15px rgba(0,0,0,0.18)'}}>♥ BEĞEN</div><div style={{flex: 1, background: C.teal, color: 'white', padding: '13px 18px', borderRadius: 14, textAlign: 'center', fontSize: 21, fontWeight: 900, boxShadow: '0 7px 15px rgba(0,0,0,0.18)'}}>✓ ABONE OL</div></div>}
    <Audio src={staticFile(`audio/matematik/dogru/${scene.id}.mp3`)}/>
  </AbsoluteFill>;
};

export const Dogru: React.FC = () => <AbsoluteFill style={{background: '#E8F5F2'}}>{scenes.map((scene, index) => <Sequence key={scene.id} from={Math.round(scenes.slice(0, index).reduce((sum, previous) => sum + previous.totalSec, 0) * 30)} durationInFrames={Math.round(scene.totalSec * 30)}><SceneView scene={scene}/></Sequence>)}</AbsoluteFill>;

export const DogruConfig = {id: 'Dogru', fps: 30, width: 960, height: 540, durationInFrames: Math.round(scenes.reduce((sum, scene) => sum + scene.totalSec, 0) * 30)};
