import React from 'react';
import {AbsoluteFill, Audio, Img, Sequence, interpolate, spring, staticFile, useCurrentFrame, useVideoConfig} from 'remotion';
import {GifCharacter} from '../GifCharacter';

const C={navy:'#173B66',blue:'#2877C7',red:'#E94F5F',amber:'#F6BC46',mint:'#34A985',violet:'#7456B8',ink:'#172638'};
const clamp={extrapolateLeft:'clamp' as const,extrapolateRight:'clamp' as const};
const sceneFrames=210;

const Background:React.FC<{accent:string}>=({accent})=>{const f=useCurrentFrame();return <AbsoluteFill style={{background:'linear-gradient(145deg,#F7FBFF 0%,#FFFFFF 48%,#FFF5EF 100%)',overflow:'hidden'}}><div style={{position:'absolute',inset:0,opacity:.24,backgroundImage:'linear-gradient(rgba(40,119,199,.16) 2px,transparent 2px),linear-gradient(90deg,rgba(40,119,199,.16) 2px,transparent 2px)',backgroundSize:'72px 72px'}}/><div style={{position:'absolute',width:700,height:700,borderRadius:'50%',left:-340,top:-300,background:`${accent}18`,transform:`translateY(${Math.sin(f/20)*18}px)`}}/><div style={{position:'absolute',width:640,height:640,borderRadius:'50%',right:-280,bottom:-330,background:'rgba(40,119,199,.10)',transform:`translateY(${Math.cos(f/24)*15}px)`}}/></AbsoluteFill>};

const Brand:React.FC=()=>{const f=useCurrentFrame();const p=spring({frame:f,fps:30,config:{damping:14,stiffness:100}});return <Img src={staticFile('images/ders-kutusu-logo.png')} style={{position:'absolute',left:52,top:28,width:205,height:137,objectFit:'contain',opacity:p,transform:`translateY(${(1-p)*-24}px) scale(${.9+p*.1})`,filter:'drop-shadow(0 13px 20px rgba(23,59,102,.20))'}}/>};

const Title:React.FC<{eyebrow:string;title:string;body:string;accent:string}>=({eyebrow,title,body,accent})=>{const f=useCurrentFrame();const {fps}=useVideoConfig();const a=spring({frame:f-5,fps,config:{damping:15,stiffness:92}});return <div style={{position:'absolute',left:105,top:250,width:1120,opacity:a,transform:`translateX(${(1-a)*-70}px)`}}><div style={{display:'inline-flex',padding:'13px 22px',borderRadius:999,background:accent,color:'#fff',fontSize:21,fontWeight:950,letterSpacing:2}}>{eyebrow}</div><div style={{fontSize:82,lineHeight:1.02,fontWeight:950,color:C.navy,marginTop:27,letterSpacing:-2.5}}>{title}</div><div style={{fontSize:31,lineHeight:1.45,fontWeight:750,color:'#506579',marginTop:27,maxWidth:980}}>{body}</div></div>};

const SubjectCards:React.FC=()=>{const f=useCurrentFrame();const {fps}=useVideoConfig();const items=[['TÜRKÇE',C.red,'Aa'],['MATEMATİK',C.blue,'π'],['FEN',C.mint,'⚗'],['SOSYAL',C.violet,'◎']];return <div style={{position:'absolute',left:100,top:690,display:'flex',gap:22}}>{items.map((x,i)=>{const p=spring({frame:f-28-i*7,fps,config:{damping:12,stiffness:120}});return <div key={x[0]} style={{width:245,height:145,borderRadius:30,background:'#fff',border:`4px solid ${x[1]}`,boxShadow:'0 18px 40px rgba(23,59,102,.12)',display:'flex',alignItems:'center',gap:16,padding:'0 22px',opacity:p,transform:`translateY(${(1-p)*42}px) scale(${.9+p*.1})`}}><div style={{width:66,height:66,borderRadius:20,background:`${x[1]}18`,color:x[1],display:'flex',alignItems:'center',justifyContent:'center',fontSize:35,fontWeight:950}}>{x[2]}</div><div style={{fontSize:23,fontWeight:950,color:C.navy}}>{x[0]}</div></div>})}</div>};

const Method:React.FC=()=>{const f=useCurrentFrame();const {fps}=useVideoConfig();const items=[['1','KISA ANLATIM','Konu, gereksiz ayrıntı olmadan açıklanır.'],['2','HAREKETLİ ÖRNEK','Bilgi, özgün görsellerle görünür hâle gelir.'],['3','HIZLI KONTROL','Mini soruyla öğrenme hemen pekişir.']];return <div style={{position:'absolute',left:100,top:260,width:1110,display:'grid',gap:24}}>{items.map((x,i)=>{const p=spring({frame:f-6-i*13,fps,config:{damping:13,stiffness:105}});return <div key={x[0]} style={{height:185,borderRadius:36,background:'#fff',border:'3px solid #D9E8F5',boxShadow:'0 19px 48px rgba(23,59,102,.12)',display:'flex',alignItems:'center',gap:30,padding:'0 38px',opacity:p,transform:`translateX(${(1-p)*-55}px)`}}><div style={{width:92,height:92,borderRadius:29,background:[C.red,C.amber,C.mint][i],color:'#fff',display:'flex',alignItems:'center',justifyContent:'center',fontSize:48,fontWeight:950}}>{x[0]}</div><div><div style={{fontSize:31,fontWeight:950,color:C.navy}}>{x[1]}</div><div style={{fontSize:23,color:'#61768A',fontWeight:750,marginTop:12}}>{x[2]}</div></div><div style={{marginLeft:'auto',fontSize:54,color:[C.red,C.amber,C.mint][i],transform:`translateX(${Math.sin(f/10+i)*5}px)`}}>→</div></div>})}</div>};

const Phone:React.FC=()=>{const f=useCurrentFrame();const {fps}=useVideoConfig();const p=spring({frame:f-5,fps,config:{damping:14,stiffness:95}});const count=Math.max(1,5-Math.floor((f%150)/30));return <div style={{position:'absolute',left:200,top:170,width:450,height:760,borderRadius:62,background:'#172638',padding:18,boxShadow:'0 35px 80px rgba(23,38,56,.3)',opacity:p,transform:`translateY(${(1-p)*55}px) rotate(-3deg)`}}><div style={{height:'100%',borderRadius:46,background:'linear-gradient(165deg,#EAF5FF,#FFFFFF 55%,#FFF0EA)',position:'relative',overflow:'hidden'}}><div style={{height:90,background:C.navy,color:'#fff',display:'flex',alignItems:'center',padding:'0 30px',fontSize:26,fontWeight:950}}>DERS KUTUSU • SHORTS</div><div style={{margin:30,padding:28,borderRadius:28,background:'#fff',boxShadow:'0 15px 35px rgba(23,59,102,.13)',fontSize:29,fontWeight:950,color:C.navy}}>Üç seçenekten doğru olanı bul!</div><div style={{display:'grid',gap:16,padding:'0 30px'}}>{['A','B','C'].map((x,i)=><div key={x} style={{height:90,borderRadius:24,background:'#fff',border:`4px solid ${i===1?C.violet:'#D8E6F3'}`,display:'flex',alignItems:'center',padding:'0 24px',gap:20,fontSize:27,fontWeight:900,color:C.ink}}><span style={{width:50,height:50,borderRadius:15,background:`${C.violet}18`,display:'flex',alignItems:'center',justifyContent:'center',color:C.violet}}>{x}</span>Seçenek</div>)}</div><div style={{position:'absolute',left:145,bottom:55,width:125,height:125,borderRadius:'50%',background:'#fff',boxShadow:'0 16px 40px rgba(23,59,102,.2)',display:'flex',alignItems:'center',justifyContent:'center',fontSize:60,fontWeight:950,color:C.violet}}>{count}</div></div></div>};

const Scene:React.FC<{index:number}>=({index})=>{const f=useCurrentFrame();const talking=true;if(index===0)return <AbsoluteFill><Background accent={C.blue}/><Brand/><Title eyebrow="5. SINIF DERSLERİ" title="Kısa, anlaşılır, görsel." body="Ders Kutusu; konuları düzenli, sade ve akılda kalıcı bir öğrenme deneyimine dönüştürür." accent={C.red}/><SubjectCards/><GifCharacter name="filiz" x={1640} y={560} scale={2.65} animate={talking}/></AbsoluteFill>;if(index===1)return <AbsoluteFill><Background accent={C.amber}/><Brand/><div style={{position:'absolute',left:100,top:190,fontSize:54,fontWeight:950,color:C.navy}}>Nasıl öğreniyoruz?</div><Method/><GifCharacter name="ibrahim" x={1640} y={560} scale={2.65} flip animate={talking}/></AbsoluteFill>;return <AbsoluteFill><Background accent={C.violet}/><Brand/><Phone/><div style={{position:'absolute',left:790,top:260,width:780}}><div style={{fontSize:23,fontWeight:950,letterSpacing:2.5,color:C.violet}}>MİNİ SORULAR • SHORTS</div><div style={{fontSize:72,lineHeight:1.05,fontWeight:950,color:C.navy,marginTop:20}}>Öğrendiğini hemen kontrol et.</div><div style={{fontSize:29,lineHeight:1.45,color:'#5A7085',fontWeight:750,marginTop:30}}>Üç seçenek, düşünme süresi ve net cevaplarla bilgini hızlıca pekiştir.</div></div><GifCharacter name="filiz" x={1690} y={430} scale={2.25} animate={talking}/></AbsoluteFill>};

export const ChannelTrailer:React.FC=()=>{const f=useCurrentFrame();const fade=(start:number,end:number)=>interpolate(f,[start,start+12,end-12,end],[0,1,1,0],clamp);return <AbsoluteFill style={{fontFamily:'Trebuchet MS,Arial,sans-serif',background:'#fff'}}><Sequence from={0} durationInFrames={sceneFrames}><div style={{position:'absolute',inset:0,opacity:fade(0,sceneFrames)}}><Scene index={0}/></div><Audio src={staticFile('audio/channel_trailer/01.mp3')}/></Sequence><Sequence from={sceneFrames} durationInFrames={sceneFrames}><div style={{position:'absolute',inset:0,opacity:fade(sceneFrames,sceneFrames*2)}}><Scene index={1}/></div><Audio src={staticFile('audio/channel_trailer/02.mp3')}/></Sequence><Sequence from={sceneFrames*2} durationInFrames={sceneFrames}><div style={{position:'absolute',inset:0,opacity:fade(sceneFrames*2,sceneFrames*3)}}><Scene index={2}/></div><Audio src={staticFile('audio/channel_trailer/03.mp3')}/></Sequence></AbsoluteFill>};

export const ChannelTrailerConfig={id:'ChannelTrailer',fps:30,width:1920,height:1080,durationInFrames:630};
