import React from 'react';
import {
  AbsoluteFill,
  Audio,
  Easing,
  Sequence,
  interpolate,
  spring,
  staticFile,
  useCurrentFrame,
  useVideoConfig,
} from 'remotion';
import {GifCharacter} from '../../GifCharacter';
import allTimings from './lesson_shorts_timings.json';

const palette = {
  navy: '#173B66', blue: '#2877C7', red: '#D8505B', coral: '#F28A7E',
  amber: '#F6BC46', mint: '#34A985', violet: '#7456B8', ink: '#172638',
};

export const lessonSpecs = {
  ay: {subject: 'FEN BİLİMLERİ', topic: 'AY’IN EVRELERİ', question: "Ay'ın dört ana evresi nelerdir?", answer: 'Yeni ay, ilk dördün, dolunay ve son dördün.', choices: ['Hilal, şişkin ay, dolunay', 'Yeni ay, ilk dördün, dolunay, son dördün', 'Güneş, Dünya, Ay, yıldız'], correct: 1, hint: 'ANA EVRELER YAKLAŞIK BİRER HAFTA ARAYLA GÖRÜLÜR', visual: 'moon', accent: palette.violet},
  gunes: {subject: 'FEN BİLİMLERİ', topic: 'GÜNEŞ’İN YAPISI', question: "Güneş'in çapı, Dünya'nın çapının yaklaşık kaç katıdır?", answer: 'Güneş’in çapı Dünya’nın yaklaşık 109 katıdır.', choices: ['4 kat', '109 kat', '332 bin kat'], correct: 1, hint: 'GÜNEŞ, GÜNEŞ SİSTEMİMİZDEKİ TEK YILDIZDIR', visual: 'sun', accent: palette.amber},
  nokta: {subject: 'MATEMATİK', topic: 'GEOMETRİ', question: 'Boyutu olmayan ama bir konum belirten geometrik kavram nedir?', answer: 'Bu geometrik kavram noktadır.', choices: ['Doğru', 'Işın', 'Nokta'], correct: 2, hint: 'YALNIZCA BİR KONUM BELİRTİR', visual: 'point', accent: palette.red},
  dogruparcasi: {subject: 'MATEMATİK', topic: 'GEOMETRİ', question: 'İki noktayı birleştiren en kısa düz çizgiye ne denir?', answer: 'İki uçlu bu şekle doğru parçası denir.', choices: ['Doğru', 'Doğru parçası', 'Işın'], correct: 1, hint: 'İKİ UÇ NOKTASI VARDIR VE UZUNLUĞU ÖLÇÜLEBİLİR', visual: 'segment', accent: palette.mint},
  isin: {subject: 'MATEMATİK', topic: 'GEOMETRİ', question: 'Bir noktadan başlayıp tek yönde sonsuza uzanan düz çizgi nedir?', answer: 'Bir ucu sabit bu şekil ışındır.', choices: ['Doğru parçası', 'Işın', 'Doğru'], correct: 1, hint: 'BAŞLANGIÇ NOKTASI VAR; BİTİŞ NOKTASI YOK', visual: 'ray', accent: palette.amber},
  dogru: {subject: 'MATEMATİK', topic: 'GEOMETRİ', question: 'İki yönde sonsuza uzanan, uç noktası olmayan düz çizgi nedir?', answer: 'İki yönde uzayan bu şekil doğrudur.', choices: ['Işın', 'Doğru parçası', 'Doğru'], correct: 2, hint: 'İKİ YÖNDE DE SONSUZA UZANIR', visual: 'line', accent: palette.blue},
  cumle_genel: {subject: 'TÜRKÇE', topic: 'CÜMLEDE KONU', question: 'Bir cümlenin konusunu bulmak için hangi soruyu sorarız?', answer: '“Bu cümlede neyden söz ediliyor?” diye sorarız.', choices: ['Kim yaptı?', 'Nerede oldu?', 'Neyden söz ediliyor?'], correct: 2, hint: 'KONU, CÜMLEDE ÜZERİNDE DURULAN DÜŞÜNCEDİR', visual: 'sentence', accent: palette.blue},
  es_zit_anlam: {subject: 'TÜRKÇE', topic: 'ANLAM İLİŞKİLERİ', question: 'Ev-hane ve yaz-kış çiftlerinden hangisi zıt anlamlıdır?', answer: 'Yaz-kış zıt; ev-hane eş anlamlıdır.', choices: ['Ev – hane', 'Yaz – kış', 'Okul – mektep'], correct: 1, hint: 'ZIT ANLAMLI SÖZCÜKLER KARŞIT KAVRAMLARI ANLATIR', visual: 'meaning', accent: palette.red},
  somut_soyut: {subject: 'TÜRKÇE', topic: 'SÖZCÜKTE ANLAM', question: 'Sevgi sözcüğü somut mu, soyut mu?', answer: 'Sevgi soyuttur; beş duyumuzla algılanamaz.', choices: ['Somut', 'Soyut', 'Terim'], correct: 1, hint: 'BEŞ DUYUYLA ALGILANIP ALGILANAMADIĞINI DÜŞÜN', visual: 'abstract', accent: palette.violet},
  tur: {subject: 'TÜRKÇE', topic: 'HİKÂYE TÜRÜ', question: 'Hikâyenin üç ana bölümü nelerdir?', answer: 'Serim, düğüm ve çözüm.', choices: ['Serim, düğüm, çözüm', 'Kişi, yer, zaman', 'Giriş, başlık, sonuç'], correct: 0, hint: 'OLAYIN BAŞLAMASI, GELİŞMESİ VE SONUÇLANMASINI DÜŞÜN', visual: 'story', accent: palette.mint},
  kulturel_1: {subject: 'SOSYAL BİLGİLER', topic: 'KÜLTÜR', question: 'Bir toplumun kuşaktan kuşağa aktardığı maddi ve manevi değerlerin tümüne ne denir?', answer: 'Kültür denir.', choices: ['Kültür', 'Coğrafya', 'Ekonomi'], correct: 0, hint: 'TOPLUMUN ORTAK KİMLİĞİNİ DÜŞÜN', visual: 'culture', accent: palette.red},
  kulturel_2: {subject: 'SOSYAL BİLGİLER', topic: 'KÜLTÜR ÖGELERİ', question: 'Aşağıdakilerden hangisi manevi kültür ögesidir?', answer: 'Türküler manevi kültür ögesidir.', choices: ['Mimari eserler', 'Türküler', 'Giysiler'], correct: 1, hint: 'DUYGU VE DÜŞÜNCELERİ AKTARAN ÖGEYİ BUL', visual: 'culture', accent: palette.violet},
  kulturel_3: {subject: 'SOSYAL BİLGİLER', topic: 'HALK OYUNLARI', question: 'Karadeniz Bölgesi ile özdeşleşen halk oyunu hangisidir?', answer: 'Karadeniz ile özdeşleşen oyun horondur.', choices: ['Zeybek', 'Hora', 'Horon'], correct: 2, hint: 'KARADENİZ’İN HIZLI VE HAREKETLİ OYUNUNU DÜŞÜN', visual: 'culture', accent: palette.blue},
  kulturel_4: {subject: 'SOSYAL BİLGİLER', topic: 'EL SANATLARI', question: 'Aşağıdakilerden hangisi geleneksel el sanatlarımızdan biridir?', answer: 'Çinicilik geleneksel el sanatlarımızdandır.', choices: ['Çinicilik', 'Futbol', 'Astronomi'], correct: 0, hint: 'EMEKLE ÜRETİLEN GELENEKSEL SANATI BUL', visual: 'culture', accent: palette.mint},
  kuvvet_1: {subject: 'FEN BİLİMLERİ', topic: 'KUVVETİN BİRİMİ', question: 'Kuvvetin birimi aşağıdakilerden hangisidir?', answer: 'Kuvvetin birimi Newton’dur.', choices: ['Metre', 'Newton', 'Kilogram'], correct: 1, hint: 'ÜÇ SEÇENEĞİ DİKKATLE KARŞILAŞTIR', visual: 'force', accent: palette.red},
  kuvvet_2: {subject: 'FEN BİLİMLERİ', topic: 'KUVVETİN ÖLÇÜLMESİ', question: 'Kuvvetin büyüklüğünü ölçen araç hangisidir?', answer: 'Kuvvet dinamometreyle ölçülür.', choices: ['Termometre', 'Eşit kollu terazi', 'Dinamometre'], correct: 2, hint: 'DOĞRU ÖLÇÜM ARACINI SEÇ', visual: 'force', accent: palette.blue},
} as const;

export type LessonSlug = keyof typeof lessonSpecs;
type Timing = typeof allTimings[LessonSlug];
const sec = (value: number, fps: number) => Math.round(value * fps);
const CONGRATS_DELAY_SECONDS = 1;
const CONGRATS_HOLD_SECONDS = 1.2;

const Background: React.FC<{accent: string}> = ({accent}) => {
  const frame = useCurrentFrame();
  return <AbsoluteFill style={{background: 'linear-gradient(165deg,#EAF5FF 0%,#FFFFFF 47%,#FFF3EF 100%)', overflow: 'hidden', fontFamily: 'Verdana,Arial,sans-serif'}}>
    <div style={{position: 'absolute', width: 760, height: 760, borderRadius: '50%', left: -390, top: 420, background: 'rgba(40,119,199,.08)', transform: `translateY(${Math.sin(frame / 28) * 18}px)`}}/>
    <div style={{position: 'absolute', width: 660, height: 660, borderRadius: '50%', right: -340, top: 15, background: `${accent}16`, transform: `translateY(${Math.cos(frame / 34) * 16}px)`}}/>
    {Array.from({length: 8}).map((_, i) => <div key={i} style={{position: 'absolute', left: 75 + (i * 173) % 920, top: 130 + (i * 239) % 1530, width: 10 + i % 3 * 6, height: 10 + i % 3 * 6, borderRadius: i % 2 ? 4 : '50%', background: i % 3 ? 'rgba(40,119,199,.15)' : `${accent}45`, transform: `translateY(${Math.sin(frame / 16 + i) * 13}px) rotate(${frame * (i % 2 ? .4 : -.25)}deg)`}}/>)}
  </AbsoluteFill>;
};

const Pill: React.FC<{children: React.ReactNode; color: string}> = ({children, color}) => <div style={{padding: '14px 24px', borderRadius: 999, background: color, color: '#fff', fontSize: 27, fontWeight: 950, letterSpacing: 1.5, boxShadow: '0 10px 28px rgba(23,59,102,.16)'}}>{children}</div>;

const Header: React.FC<{subject: string; accent: string}> = ({subject, accent}) => {
  const frame = useCurrentFrame();
  const enter = interpolate(frame,[0,18],[0,1],{extrapolateLeft:'clamp',extrapolateRight:'clamp',easing:Easing.out(Easing.cubic)});
  return <div style={{position: 'absolute', left: 62, right: 62, top: 70, display: 'flex', alignItems: 'center', gap: 18, transform: `translateY(${(1 - enter) * -36}px)`, opacity: enter}}>
    <Pill color={palette.navy}>5. SINIF</Pill><Pill color={accent}>{subject}</Pill>
    <div style={{height: 4, flex: 1, borderRadius: 99, background: 'linear-gradient(90deg,#BFD9F2,rgba(191,217,242,0))'}}/>
  </div>;
};

const QuestionCard: React.FC<{spec: typeof lessonSpecs[LessonSlug]; waiting: boolean}> = ({spec, waiting}) => {
  const frame = useCurrentFrame(); const {fps} = useVideoConfig();
  const enter = spring({frame: frame - 3, fps, config: {damping: 14, stiffness: 105}});
  const fontSize = spec.question.length > 62 ? 42 : spec.question.length > 48 ? 45 : 49;
  return <div style={{position: 'absolute', left: 64, right: 64, top: 170, height: 355, borderRadius: 42, background: '#fff', border: '4px solid #D4E5F5', boxShadow: '0 26px 70px rgba(23,59,102,.16)', padding: '38px 42px', transform: `translateY(${(1 - enter) * 55}px) scale(${.96 + enter * .04})`, overflow: 'hidden'}}>
    <div style={{position: 'absolute', right: -44, top: -55, width: 220, height: 220, borderRadius: '50%', background: spec.accent, opacity: .15}}/>
    <div style={{display: 'flex', alignItems: 'center', gap: 22}}>
      <div style={{width: 92, height: 92, flex: '0 0 92px', borderRadius: 28, background: palette.amber, color: palette.navy, display: 'flex', alignItems: 'center', justifyContent: 'center', fontWeight: 950, fontSize: 60, transform: `scale(${waiting ? 1 + Math.sin(frame / 8) * .025 : 1}) rotate(${Math.sin(frame / 12) * 2}deg)`, boxShadow: '0 12px 24px rgba(246,188,70,.30)'}}>?</div>
      <div><div style={{color: spec.accent, fontSize: 25, fontWeight: 950, letterSpacing: 2}}>HIZLI SORU • {spec.topic}</div><div style={{color: palette.ink, fontSize, lineHeight: 1.14, fontWeight: 950, marginTop: 10}}>{spec.question}</div></div>
    </div>
    <div style={{position: 'absolute', left: 42, bottom: 28, maxWidth: 840, padding: '11px 20px', borderRadius: 16, background: '#EDF5FC', color: palette.navy, fontWeight: 900, fontSize: 19, letterSpacing: .2}}>{spec.hint}</div>
  </div>;
};

const Stage: React.FC<{children: React.ReactNode}> = ({children}) => <div style={{position: 'absolute', left: 64, right: 64, top: 575, height: 570}}>{children}</div>;
const labelStyle: React.CSSProperties = {fontWeight: 950, color: palette.navy, fontSize: 25, textAlign: 'center'};

const MoonVisual: React.FC<{revealed: boolean; revealFrame: number}> = ({revealed, revealFrame}) => {
  const frame = useCurrentFrame(); const {fps} = useVideoConfig();
  const phases = [{x: 55,y: 75,n:'YENİ AY',kind:0},{x: 360,y: 15,n:'İLK DÖRDÜN',kind:1},{x: 665,y: 75,n:'DOLUNAY',kind:2},{x: 360,y: 325,n:'SON DÖRDÜN',kind:3}];
  return <Stage><div style={{position: 'absolute', left: 210, top: 20, width: 520, height: 500, border: '5px dashed #C5D4E5', borderRadius: '50%', transform: `rotate(${frame * .03}deg)`}}/>
    <div style={{position:'absolute',left:406,top:205,width:130,height:130,borderRadius:'50%',background:'radial-gradient(circle at 35% 30%,#6DB9F2,#2877C7 65%,#173B66)',boxShadow:'0 18px 38px rgba(23,59,102,.25)'}}/>
    {phases.map((p,i)=>{const e=spring({frame:frame-8-i*4,fps,config:{damping:12,stiffness:120}});const r=spring({frame:frame-revealFrame-i*4,fps,config:{damping:10,stiffness:150}});return <div key={p.n} style={{position:'absolute',left:p.x,top:p.y,width:230,transform:`scale(${.8+e*.2}) translateY(${Math.sin(frame/18+i)*5}px)`,opacity:e}}><div style={{position:'relative',margin:'0 auto',width:115,height:115,borderRadius:'50%',overflow:'hidden',background:p.kind===2?'#FFF5C7':'#15233A',boxShadow:'0 12px 28px rgba(23,38,56,.24)',border:'5px solid #fff'}}>{p.kind===1&&<div style={{position:'absolute',right:0,top:0,width:'50%',height:'100%',background:'#FFF5C7'}}/>}{p.kind===3&&<div style={{position:'absolute',left:0,top:0,width:'50%',height:'100%',background:'#FFF5C7'}}/>}</div><div style={{...labelStyle,marginTop:10,opacity:revealed?r:1,color:revealed?palette.violet:'#8391A2'}}>{revealed?p.n:`${i+1}. EVRE`}</div></div>})}
  </Stage>;
};

const SunVisual: React.FC<{revealed: boolean; revealFrame: number}> = ({revealed, revealFrame}) => {
  const frame=useCurrentFrame(); const {fps}=useVideoConfig(); const pop=spring({frame:frame-9,fps,config:{damping:13,stiffness:100}}); const ans=spring({frame:frame-revealFrame,fps,config:{damping:10,stiffness:150}});
  return <Stage><div style={{position:'absolute',left:72,top:95,width:330,height:330,borderRadius:'50%',background:'radial-gradient(circle,#FFF6A6 0%,#F6BC46 45%,#F28A3B 72%,#D8505B 100%)',boxShadow:'0 0 0 25px rgba(246,188,70,.15),0 0 70px rgba(246,188,70,.55)',transform:`scale(${.82+pop*.18}) rotate(${frame*.08}deg)`}}>{Array.from({length:12}).map((_,i)=><div key={i} style={{position:'absolute',left:153,top:-38,width:24,height:56,borderRadius:20,background:palette.amber,transformOrigin:'12px 203px',transform:`rotate(${i*30}deg) scaleY(${1+Math.sin(frame/9+i)*.12})`}}/>)}</div>
    <div style={{position:'absolute',right:92,top:190,width:130,height:130,borderRadius:'50%',background:'radial-gradient(circle at 35% 30%,#77C8F2,#2877C7 70%,#173B66)',boxShadow:'0 14px 32px rgba(23,59,102,.28)'}}/>
    <div style={{position:'absolute',left:420,top:205,width:300,height:95,borderRadius:30,background:'#fff',border:`4px solid ${palette.amber}`,display:'flex',alignItems:'center',justifyContent:'center',boxShadow:'0 15px 35px rgba(23,59,102,.14)',fontSize:revealed?53:65,fontWeight:950,color:palette.navy,transform:`scale(${revealed?.9+ans*.1:1})`}}>{revealed?'109 KAT':'? KAT'}</div>
    <div style={{position:'absolute',left:160,top:465,...labelStyle}}>GÜNEŞ</div><div style={{position:'absolute',right:108,top:345,...labelStyle}}>DÜNYA</div>
  </Stage>;
};

const GeometryVisual: React.FC<{kind:'point'|'segment'|'ray'|'line'; revealed:boolean; accent:string; revealFrame:number}> = ({kind,revealed,accent,revealFrame}) => {
  const frame=useCurrentFrame(); const {fps}=useVideoConfig(); const draw=interpolate(frame,[12,55],[0,1],{extrapolateLeft:'clamp',extrapolateRight:'clamp',easing:Easing.out(Easing.cubic)}); const ans=spring({frame:frame-revealFrame,fps,config:{damping:11,stiffness:145}});
  if(kind==='point') return <Stage><div style={{position:'absolute',inset:'20px 40px 50px',borderRadius:45,background:'#fff',border:'4px solid #D5E5F4',boxShadow:'0 20px 50px rgba(23,59,102,.13)'}}><div style={{position:'absolute',left:390,top:145,width:95,height:95,borderRadius:'50%',background:accent,boxShadow:`0 0 0 ${20+Math.sin(frame/8)*8}px ${accent}25`,transform:`scale(${.85+Math.sin(frame/10)*.05})`}}/><div style={{position:'absolute',left:405,top:265,width:65,textAlign:'center',fontSize:34,fontWeight:950,color:palette.navy}}>A</div><div style={{position:'absolute',left:205,top:360,fontSize:26,fontWeight:900,color:'#718096'}}>KALEM UCUNDAKİ İZ</div><div style={{position:'absolute',right:160,top:40,fontSize:50,transform:`rotate(${Math.sin(frame/14)*8}deg)`}}>✦</div></div>{revealed&&<div style={{position:'absolute',left:295,top:455,width:365,height:78,borderRadius:25,background:accent,color:'#fff',display:'flex',alignItems:'center',justifyContent:'center',fontSize:40,fontWeight:950,transform:`scale(${.8+ans*.2})`}}>NOKTA</div>}</Stage>;
  const left=kind==='line'?90:150; const width=kind==='segment'?650:kind==='ray'?720:780;
  return <Stage><div style={{position:'absolute',inset:'28px 30px 48px',borderRadius:45,background:'#fff',border:'4px solid #D5E5F4',boxShadow:'0 20px 50px rgba(23,59,102,.13)'}}><svg width="892" height="480" viewBox="0 0 892 480"><line x1={left} y1="235" x2={left+width*draw} y2="235" stroke={accent} strokeWidth="15" strokeLinecap="round"/>{kind!=='segment'&&kind!=='point'&&<polygon points={`${left+width*draw},235 ${left+width*draw-34},211 ${left+width*draw-34},259`} fill={accent}/>} {kind==='line'&&<polygon points={`${left},235 ${left+34},211 ${left+34},259`} fill={accent}/>}<circle cx={kind==='line'?300:left} cy="235" r="16" fill={palette.navy}/><circle cx={kind==='segment'?left+width:kind==='line'?590:left+350} cy="235" r="16" fill={palette.navy}/></svg><div style={{position:'absolute',left:(kind==='line'?300:left)-16,top:275,fontSize:31,fontWeight:950,color:palette.navy}}>A</div><div style={{position:'absolute',left:(kind==='segment'?left+width:kind==='line'?590:left+350)-16,top:275,fontSize:31,fontWeight:950,color:palette.navy}}>B</div>{revealed&&<div style={{position:'absolute',left:255,top:345,width:380,height:78,borderRadius:25,background:accent,color:'#fff',display:'flex',alignItems:'center',justifyContent:'center',fontSize:38,fontWeight:950,transform:`scale(${.8+ans*.2})`}}>{kind==='segment'?'DOĞRU PARÇASI':kind==='ray'?'IŞIN':'DOĞRU'}</div>}</div></Stage>;
};

const SentenceVisual: React.FC<{revealed:boolean; accent:string; revealFrame:number}> = ({revealed,accent,revealFrame}) => {const frame=useCurrentFrame();const {fps}=useVideoConfig();const p=spring({frame:frame-revealFrame,fps,config:{damping:10,stiffness:145}});return <Stage><div style={{position:'absolute',left:55,right:55,top:50,height:340,borderRadius:42,background:'#fff',border:'4px solid #D7E6F4',boxShadow:'0 20px 50px rgba(23,59,102,.14)',padding:'65px 55px'}}><div style={{fontSize:38,lineHeight:1.35,fontWeight:900,color:palette.ink}}>“Kitap okumak hayal gücümüzü geliştirir.”</div><div style={{height:8,borderRadius:99,background:accent,marginTop:30,width:`${interpolate(frame,[20,70],[0,100],{extrapolateLeft:'clamp',extrapolateRight:'clamp'})}%`}}/>{revealed&&<div style={{marginTop:42,padding:'20px 26px',borderRadius:22,background:accent,color:'#fff',fontSize:31,fontWeight:950,transform:`scale(${.85+p*.15})`}}>NEYDEN SÖZ EDİLİYOR?</div>}<div style={{position:'absolute',right:35,bottom:-70,width:150,height:150,borderRadius:'50%',border:`15px solid ${accent}`,transform:`rotate(-20deg) translateY(${Math.sin(frame/10)*5}px)`}}/><div style={{position:'absolute',right:8,bottom:-105,width:27,height:110,borderRadius:20,background:accent,transform:'rotate(-45deg)'}}/></div></Stage>};

const MeaningVisual: React.FC<{revealed:boolean; revealFrame:number}> = ({revealed,revealFrame}) => {const frame=useCurrentFrame();const {fps}=useVideoConfig();return <Stage>{[{a:'EV',b:'HANE',tag:'EŞ ANLAMLI',color:palette.blue,y:45},{a:'YAZ',b:'KIŞ',tag:'ZIT ANLAMLI',color:palette.red,y:300}].map((v,i)=>{const e=spring({frame:frame-10-i*8,fps,config:{damping:12,stiffness:115}});const a=spring({frame:frame-revealFrame-i*5,fps,config:{damping:9,stiffness:155}});return <div key={v.a} style={{position:'absolute',left:70,right:70,top:v.y,height:190,borderRadius:38,background:'#fff',border:`4px solid ${v.color}`,boxShadow:'0 17px 40px rgba(23,59,102,.13)',display:'flex',alignItems:'center',justifyContent:'center',gap:45,transform:`translateX(${(1-e)*(i?-55:55)}px)`,opacity:e}}><div style={{fontSize:46,fontWeight:950,color:palette.navy}}>{v.a}</div><div style={{fontSize:55,color:v.color,fontWeight:950}}>↔</div><div style={{fontSize:46,fontWeight:950,color:palette.navy}}>{v.b}</div><div style={{position:'absolute',right:24,top:22,padding:'10px 15px',borderRadius:14,background:revealed?v.color:'#E8EEF4',color:revealed?'#fff':'#7C8997',fontSize:18,fontWeight:950,transform:`scale(${revealed?.8+a*.2:1})`}}>{revealed?v.tag:'HANGİSİ?'}</div></div>})}</Stage>};

const AbstractVisual: React.FC<{revealed:boolean; revealFrame:number}> = ({revealed,revealFrame}) => {const frame=useCurrentFrame();const {fps}=useVideoConfig();const a=spring({frame:frame-revealFrame,fps,config:{damping:9,stiffness:150}});const senses=['GÖRME','İŞİTME','KOKLAMA','TATMA','DOKUNMA'];return <Stage><div style={{position:'absolute',left:341,top:170,width:270,height:170,borderRadius:48,background:'linear-gradient(145deg,#8B6AC7,#62419F)',color:'#fff',display:'flex',alignItems:'center',justifyContent:'center',fontSize:53,fontWeight:950,boxShadow:'0 22px 50px rgba(116,86,184,.3)',transform:`scale(${1+Math.sin(frame/12)*.025})`}}>SEVGİ</div>{senses.map((s,i)=>{const angle=(-155+i*77)*Math.PI/180;const x=405+Math.cos(angle)*315;const y=215+Math.sin(angle)*190;return <div key={s} style={{position:'absolute',left:x,top:y,width:150,height:75,borderRadius:22,background:'#fff',border:'4px solid #D8E3EF',boxShadow:'0 12px 28px rgba(23,59,102,.11)',display:'flex',alignItems:'center',justifyContent:'center',fontSize:17,fontWeight:950,color:'#718096',transform:`translateY(${Math.sin(frame/12+i)*5}px)`}}>{s}{revealed&&<span style={{position:'absolute',fontSize:56,color:palette.red,opacity:.85}}>×</span>}</div>})}{revealed&&<div style={{position:'absolute',left:305,top:440,width:345,height:82,borderRadius:26,background:palette.violet,color:'#fff',fontSize:42,fontWeight:950,display:'flex',alignItems:'center',justifyContent:'center',transform:`scale(${.8+a*.2})`}}>SOYUT</div>}</Stage>};

const StoryVisual: React.FC<{revealed:boolean; revealFrame:number}> = ({revealed,revealFrame}) => {const frame=useCurrentFrame();const {fps}=useVideoConfig();const names=['SERİM','DÜĞÜM','ÇÖZÜM'];return <Stage><svg width="952" height="570"><path d="M120 350 C270 350 260 150 470 150 S660 350 830 350" fill="none" stroke="#C5D7E7" strokeWidth="10" strokeLinecap="round" strokeDasharray="18 15" strokeDashoffset={-frame*2}/></svg>{names.map((n,i)=>{const e=spring({frame:frame-12-i*9,fps,config:{damping:12,stiffness:115}});const a=spring({frame:frame-revealFrame-i*5,fps,config:{damping:9,stiffness:155}});const positions=[{x:50,y:270},{x:350,y:65},{x:650,y:270}];return <div key={n} style={{position:'absolute',left:positions[i].x,top:positions[i].y,width:250,height:170,borderRadius:38,background:'#fff',border:`5px solid ${[palette.blue,palette.red,palette.mint][i]}`,boxShadow:'0 18px 40px rgba(23,59,102,.14)',display:'flex',flexDirection:'column',alignItems:'center',justifyContent:'center',transform:`scale(${.82+e*.18}) translateY(${Math.sin(frame/15+i)*5}px)`,opacity:e}}><div style={{fontSize:28,fontWeight:950,color:'#7A8796'}}>{i+1}. BÖLÜM</div><div style={{fontSize:revealed?38:55,fontWeight:950,color:[palette.blue,palette.red,palette.mint][i],marginTop:12,transform:`scale(${revealed?.8+a*.2:1})`}}>{revealed?n:'?'}</div></div>})}</Stage>};

const CultureVisual:React.FC=()=>{const frame=useCurrentFrame();const {fps}=useVideoConfig();const items=[{t:'GELENEK',c:palette.red,x:75,y:65},{t:'TÜRKÜ',c:palette.violet,x:610,y:65},{t:'OYUN',c:palette.blue,x:75,y:325},{t:'SANAT',c:palette.mint,x:610,y:325}];return <Stage><div style={{position:'absolute',left:335,top:160,width:280,height:210,borderRadius:52,background:'linear-gradient(145deg,#173B66,#2877C7)',color:'#fff',display:'flex',alignItems:'center',justifyContent:'center',fontSize:51,fontWeight:950,boxShadow:'0 25px 58px rgba(23,59,102,.26)',transform:`scale(${1+Math.sin(frame/15)*.025})`}}>KÜLTÜR</div>{items.map((v,i)=>{const e=spring({frame:frame-7-i*6,fps,config:{damping:12,stiffness:115}});return <div key={v.t} style={{position:'absolute',left:v.x,top:v.y,width:265,height:145,borderRadius:36,background:'#fff',border:`5px solid ${v.c}`,boxShadow:'0 17px 38px rgba(23,59,102,.13)',display:'flex',alignItems:'center',justifyContent:'center',fontSize:31,fontWeight:950,color:v.c,opacity:e,transform:`scale(${.82+e*.18}) translateY(${Math.sin(frame/13+i)*5}px)`}}>{v.t}</div>})}</Stage>};

const ForceVisual:React.FC=()=>{const frame=useCurrentFrame();const {fps}=useVideoConfig();const e=spring({frame:frame-7,fps,config:{damping:12,stiffness:110}});const shift=interpolate(frame,[10,75],[0,330],{extrapolateLeft:'clamp',extrapolateRight:'clamp',easing:Easing.inOut(Easing.cubic)});return <Stage><div style={{position:'absolute',left:80,right:80,top:40,height:470,borderRadius:46,background:'#fff',border:'5px solid #D6E6F4',boxShadow:'0 22px 55px rgba(23,59,102,.14)',overflow:'hidden',opacity:e}}><svg width="792" height="470" viewBox="0 0 792 470"><defs><marker id="arrow" markerWidth="12" markerHeight="12" refX="10" refY="6" orient="auto"><path d="M0 0 12 6 0 12Z" fill={palette.red}/></marker></defs><rect x={95+shift} y="170" width="150" height="125" rx="25" fill={palette.amber} stroke={palette.navy} strokeWidth="6"/><line x1="105" y1="115" x2="670" y2="115" stroke={palette.red} strokeWidth="15" strokeLinecap="round" markerEnd="url(#arrow)"/><circle cx="105" cy="115" r="22" fill={palette.navy}/><path d="M82 340 H710" stroke="#D8E5F0" strokeWidth="8" strokeLinecap="round"/><path d="M120 370 Q396 430 672 370" fill="none" stroke={palette.blue} strokeWidth="8" strokeDasharray="18 14" strokeDashoffset={-frame*3}/>{Array.from({length:7}).map((_,i)=><circle key={i} cx={130+i*87} cy={370+Math.sin(frame/13+i)*10} r={i%2?8:12} fill={i%3===0?palette.mint:i%3===1?palette.red:palette.violet}/>)}</svg></div></Stage>};

const LessonVisual: React.FC<{spec:typeof lessonSpecs[LessonSlug];revealed:boolean;revealFrame:number}> = ({spec,revealed,revealFrame}) => {
  switch(spec.visual){case'moon':return <MoonVisual revealed={revealed} revealFrame={revealFrame}/>;case'sun':return <SunVisual revealed={revealed} revealFrame={revealFrame}/>;case'point':return <GeometryVisual kind="point" revealed={revealed} accent={spec.accent} revealFrame={revealFrame}/>;case'segment':return <GeometryVisual kind="segment" revealed={revealed} accent={spec.accent} revealFrame={revealFrame}/>;case'ray':return <GeometryVisual kind="ray" revealed={revealed} accent={spec.accent} revealFrame={revealFrame}/>;case'line':return <GeometryVisual kind="line" revealed={revealed} accent={spec.accent} revealFrame={revealFrame}/>;case'sentence':return <SentenceVisual revealed={revealed} accent={spec.accent} revealFrame={revealFrame}/>;case'meaning':return <MeaningVisual revealed={revealed} revealFrame={revealFrame}/>;case'abstract':return <AbstractVisual revealed={revealed} revealFrame={revealFrame}/>;case'story':return <StoryVisual revealed={revealed} revealFrame={revealFrame}/>;case'culture':return <CultureVisual/>;case'force':return <ForceVisual/>;}
};

const Countdown: React.FC<{progress:number;accent:string}> = ({progress,accent}) => {const frame=useCurrentFrame();const remaining=Math.max(1,Math.ceil(5-progress*5));const c=2*Math.PI*92;return <div style={{position:'absolute',left:320,top:1185,width:350,height:350,borderRadius:'50%',background:'#fff',boxShadow:'0 25px 60px rgba(23,59,102,.18)',display:'flex',alignItems:'center',justifyContent:'center',transform:`scale(${1+Math.sin(frame/4)*.035})`,zIndex:30}}><svg width="270" height="270" viewBox="0 0 220 220" style={{position:'absolute',transform:'rotate(-90deg)'}}><circle cx="110" cy="110" r="92" fill="none" stroke="#E7EEF5" strokeWidth="15"/><circle cx="110" cy="110" r="92" fill="none" stroke={accent} strokeWidth="15" strokeLinecap="round" strokeDasharray={c} strokeDashoffset={c*progress}/></svg><div style={{textAlign:'center'}}><div style={{fontSize:112,lineHeight:.9,color:palette.navy,fontWeight:950}}>{remaining}</div><div style={{fontSize:22,color:palette.red,fontWeight:950,marginTop:16,letterSpacing:2}}>DÜŞÜN!</div></div></div>};

const ChoicePanel: React.FC<{choices:readonly string[];correct:number;accent:string;start:number;reveal:boolean;revealFrame:number}> = ({choices,correct,accent,start,reveal,revealFrame}) => {const frame=useCurrentFrame();const {fps}=useVideoConfig();return <div style={{position:'absolute',left:78,right:78,top:590,height:525,display:'grid',gap:18,zIndex:32}}>{choices.map((choice,index)=>{const enter=spring({frame:frame-start-index*5,fps,config:{damping:13,stiffness:112}});const correctChoice=index===correct;const revealPop=spring({frame:frame-revealFrame,fps,config:{damping:9,stiffness:155}});const marked=reveal&&correctChoice;return <div key={choice} style={{height:150,borderRadius:32,background:marked?accent:'#fff',border:`5px solid ${marked?accent:'#D5E5F4'}`,boxShadow:marked?`0 22px 52px ${accent}42`:'0 16px 38px rgba(23,59,102,.12)',display:'flex',alignItems:'center',padding:'0 30px',gap:24,color:marked?'#fff':palette.ink,opacity:reveal&&!correctChoice?.48:enter,transform:`translateX(${(1-enter)*55}px) scale(${marked?.96+revealPop*.04:1})`}}><div style={{width:74,height:74,flex:'0 0 74px',borderRadius:22,background:marked?'#fff':`${accent}18`,border:`4px solid ${marked?'#fff':accent}`,color:marked?accent:palette.navy,display:'flex',alignItems:'center',justifyContent:'center',fontSize:38,fontWeight:950}}>{marked?'✓':String.fromCharCode(65+index)}</div><div style={{fontSize:choice.length>32?29:34,lineHeight:1.15,fontWeight:950}}>{choice}</div></div>})}</div>};

const Congrats: React.FC<{start:number;accent:string}> = ({start,accent}) => {const frame=useCurrentFrame();const {fps}=useVideoConfig();const enter=spring({frame:frame-start,fps,config:{damping:10,stiffness:135}});return <div style={{position:'absolute',left:85,right:85,top:460,height:520,borderRadius:54,background:'#fff',border:`6px solid ${accent}`,boxShadow:'0 32px 90px rgba(23,59,102,.22)',display:'flex',alignItems:'center',justifyContent:'center',transform:`translateY(${(1-enter)*70}px) scale(${.88+enter*.12})`,opacity:enter,zIndex:65}}><div style={{fontSize:88,color:palette.navy,fontWeight:950,letterSpacing:1}}>Tebrikler!</div></div>};

export const LessonShorts: React.FC<{slug:LessonSlug}> = ({slug}) => {
  const spec=lessonSpecs[slug]; const timing:Timing=allTimings[slug]; const frame=useCurrentFrame(); const {fps}=useVideoConfig();
  const qAudio=sec(timing.question_start,fps),qStart=sec(timing.question_speech_start,fps),qEnd=sec(timing.question_end,fps),aAudio=sec(timing.answer_start,fps),aStart=sec(timing.answer_speech_start,fps),aEnd=sec(timing.answer_end,fps),congratsStart=aEnd+sec(CONGRATS_DELAY_SECONDS,fps);
  const waiting=frame>=qEnd&&frame<aStart, choicesVisible=frame>=qEnd&&frame<congratsStart, congrats=frame>=congratsStart; const talking=(frame>=qStart&&frame<qEnd)||(frame>=aStart&&frame<aEnd); const progress=interpolate(frame,[qEnd,aStart],[0,1],{extrapolateLeft:'clamp',extrapolateRight:'clamp'});
  return <AbsoluteFill style={{fontFamily:'Verdana,Arial,sans-serif',color:palette.ink}}><Background accent={spec.accent}/><Header subject={spec.subject} accent={spec.accent}/>{!congrats&&<QuestionCard spec={spec} waiting={waiting}/>} {frame<qEnd&&<LessonVisual spec={spec} revealed={false} revealFrame={aStart}/>} {choicesVisible&&<ChoicePanel choices={spec.choices} correct={spec.correct} accent={spec.accent} start={qEnd} reveal={frame>=aStart} revealFrame={aStart}/>} {waiting&&<Countdown progress={progress} accent={spec.accent}/>} {congrats&&<Congrats start={congratsStart} accent={spec.accent}/>}<GifCharacter name="ibrahim" x={895} y={1495} scale={2.08} flip animate={talking}/><div style={{position:'absolute',right:38,top:1784,width:290,height:58,borderRadius:18,background:talking?palette.blue:'#6D7C8C',color:'#fff',display:'flex',alignItems:'center',justifyContent:'center',gap:12,fontSize:25,fontWeight:950,zIndex:88,border:'3px solid #fff',boxShadow:'0 10px 26px rgba(23,59,102,.22)'}}>{talking&&<span style={{width:11,height:11,borderRadius:'50%',background:'#fff',boxShadow:'0 0 0 7px rgba(255,255,255,.2)'}}/>} İBRAHİM</div><div style={{position:'absolute',left:0,right:0,bottom:0,height:34,background:`linear-gradient(90deg,${palette.navy},${palette.blue} 55%,${spec.accent})`,zIndex:120}}/><Sequence from={qAudio}><Audio src={staticFile(`audio/shorts/${slug}/question.mp3`)}/></Sequence><Sequence from={aAudio}><Audio src={staticFile(`audio/shorts/${slug}/answer.mp3`)}/></Sequence></AbsoluteFill>;
};

export const getConfig = (slug:LessonSlug) => ({id:`Short-${slug.replaceAll('_','-')}`,fps:allTimings[slug].fps,width:1080,height:1920,durationInFrames:Math.ceil((allTimings[slug].answer_end+CONGRATS_DELAY_SECONDS+CONGRATS_HOLD_SECONDS)*allTimings[slug].fps)});
